all:
  # Negations syntax from https://github.com/dorny/paths-filter/issues/184#issuecomment-2786521554
  - "src/**/!(*.{md,py,sh,gitkeep,gitignore})"
  - "test/**/!(*.{md,py,sh,gitkeep,gitignore})"
  - "public/**/!(*.{md,py,sh,gitkeep,gitignore})"
  # Workflows that can impact tests
  - ".github/workflows/test*.yml"
  - ".github/test-filters.yml"
  # top-level files
  - "package*.json"
  - ".nvrmc" # Updates to node version can break tests
  - "vite*" # vite.config.ts, vite.vitest.config.ts, vitest.workspace.ts
  - "tsconfig*.json" # tsconfig.json tweaking can impact compilation
  - "global.d.ts"
  - ".env*"