# SPDX-FileCopyrightText: 2024-2025 Pagefault Games
# SPDX-FileContributor: SirzBenjie
#
# SPDX-License-Identifier: AGPL-3.0-only

# Base settings to use
# Note that the `_cfg` key isn't part of ls-lint's configuration, it's just a YAML anchor for reuse.
_cfg: &cfg
   .ps1: kebab-case
   .ts: kebab-case
   .js: kebab-case
   .*.ts: kebab-case
   .*.js: kebab-case
   .dir: kebab-case
   .py: snake_case # python files should always use snake_case

ls:
   <<: *cfg
   src: &src
      <<: *cfg
      .dir: kebab-case | regex:@types
      .js: exists:0
   src/system/version-migration/versions:
      .ts: snake_case
      <<: *cfg
   test: *src
ignore:
   - node_modules
   - .vscode
   - .github
   - .git
   - assets
   - locales
   - dist
   - .devcontainer
   - "LICENSES"