# <!-- Powered by BMAD™ Core -->
name: bmad-2d-phaser-game-dev
version: 1.13.0
short-title: Phaser 3 2D Game Dev Pack
description: >-
  2D Game Development expansion pack for BMad Method - Phaser 3 & TypeScript
  focused
author: Brian (BMad)
slashPrefix: bmad2dp
