export enum Button {
  UP = 0,
  DOWN = 1,
  LEFT = 2,
  RIGHT = 3,
  SUBMIT = 4,
  ACTION = 5,
  CANCEL = 6,
  MENU = 7,
  STATS = 8,
  CYCLE_SHINY = 9,
  CYCLE_FORM = 10,
  CYCLE_GENDER = 11,
  CYCLE_ABILITY = 12,
  CYCLE_NATURE = 13,
  CYCLE_VARIANT = 14,
  SPEED_UP = 15,
  SLOW_DOWN = 16,
}
