export enum Challenges {
  SINGLE_GENERATION,
  SINGLE_TYPE,
  LOWER_MAX_STARTER_COST,
  LOWER_STARTER_POINTS,
  FRESH_START,
  INVERSE_BATTLE,
  FLIP_STAT,
  LIMITED_CATCH,
  LIMITED_SUPPORT,
  HARDCORE,
}
