export enum Challenges {
    SINGLE_GENERATION,
    SINGLE_TYPE,
    LOWER_MAX_STARTER_COST,
    LOWER_STARTER_POINTS,
    FRESH_START,
    INVERSE_BATTLE,
    NO_AUTO_HEAL,
    HARDCORE,
    LIMITED_CATCH,
}
