export enum Challenges {
    SINGLE_GENERATION,
    SINGLE_TYPE,
    LOWER_MAX_STARTER_COST,
    LOWER_STARTER_POINTS,
    FRESH_START,
    SPLICED_ONLY,
    DOUBLES_ONLY,
    HARDER_BOSSES,
    NUZLOCKE
}
