export enum MysteryEncounterType {
  MYSTERIOUS_CHALLENGERS,
  MYSTERIOUS_CHEST,
  DARK_DEAL,
  FIGHT_OR_FLIGHT,
  SLEEPING_SNORLAX,
  TRAINING_SESSION,
  DEPARTMENT_STORE_SALE,
  SHADY_VITAMIN_DEALER,
  FIELD_TRIP,
  SAFARI_ZONE,
  FIERY_FALLOUT
}
