export enum SpeciesFormKey {
  MEGA = "mega",
  MEGA_X = "mega-x",
  MEGA_Y = "mega-y",
  MEGA_Z = "mega-z",
  MEGA_ORIGINAL = "mega-original",
  MEGA_CURLY = "mega-curly",
  MEGA_DROOPY = "mega-droopy",
  MEGA_STRETCHY = "mega-stretchy",
  PRIMAL = "primal",
  ORIGIN = "origin",
  INCARNATE = "incarnate",
  THERIAN = "therian",
  GIGANTAMAX = "gigantamax",
  GIGANTAMAX_SINGLE = "gigantamax-single",
  GIGANTAMAX_RAPID = "gigantamax-rapid",
  ETERNAMAX = "eternamax",
}
