export const TrainerItemEffect = {
  LEVEL_INCREMENT_BOOSTER: 1,
  PRESERVE_BERRY: 2,
  HEALING_BOOSTER: 3,
  EXP_BOOSTER: 4,
  MONEY_MULTIPLIER: 5,
  HIDDEN_ABILITY_CHANCE_BOOSTER: 6,
  SHINY_RATE_BOOSTER: 7,
  CRITICAL_CATCH_CHANCE_BOOSTER: 8,
  EXTRA_REWARD: 9,

  HEAL_SHOP_COST: 10,
  DOUBLE_BATTLE_CHANCE_BOOSTER: 11,

  TEMP_STAT_STAGE_BOOSTER: 12,
  TEMP_ACCURACY_BOOSTER: 13,
  TEMP_CRIT_BOOSTER: 14,

  ENEMY_DAMAGE_BOOSTER: 15,
  ENEMY_DAMAGE_REDUCER: 16,
  ENEMY_HEAL: 17,
  ENEMY_ATTACK_STATUS_CHANCE: 18,
  ENEMY_STATUS_HEAL_CHANCE: 19,
  ENEMY_ENDURE_CHANCE: 20,
  ENEMY_FUSED_CHANCE: 21,
} as const;

export type TrainerItemEffect = (typeof TrainerItemEffect)[keyof typeof TrainerItemEffect];
