import {SettingGamepad} from "../system/settings-gamepad";
import {Button} from "../enums/buttons";

/**
 * 081f-e401 - UnlicensedSNES
 */
const pad_unlicensedSNES = {
    padID: 'keyboard',
    padType: 'keyboard',
    gamepadMapping: {
        KEY_A: 0,
        KEY_B: 0,
        KEY_C: 0,
        KEY_D: 0,
        KEY_E: 0,
        KEY_F: 0,
        KEY_G: 0,
        KEY_H: 0,
        KEY_I: 0,
        KEY_J: 0,
        KEY_K: 0,
        KEY_L: 0,
        KEY_M: 0,
        KEY_N: 0,
        KEY_O: 0,
        KEY_P: 0,
        KEY_Q: 0,
        KEY_R: 0,
        KEY_S: 0,
        KEY_T: 0,
        KEY_U: 0,
        KEY_V: 0,
        KEY_W: 0,
        KEY_X: 0,
        KEY_Y: 0,
        KEY_Z: 0,
        KEY_0: 0,
        KEY_1: 0,
        KEY_2: 0,
        KEY_3: 0,
        KEY_4: 0,
        KEY_5: 0,
        KEY_6: 0,
        KEY_7: 0,
        KEY_8: 0,
        KEY_9: 0,
        KEY_CTRL: 0,
        KEY_DEL: 0,
        KEY_END: 0,
        KEY_ENTER: 0,
        KEY_ESC: 0,
        KEY_F1: 0,
        KEY_F2: 0,
        KEY_F3: 0,
        KEY_F4: 0,
        KEY_F5: 0,
        KEY_F6: 0,
        KEY_F7: 0,
        KEY_F8: 0,
        KEY_F9: 0,
        KEY_F10: 0,
        KEY_F11: 0,
        KEY_F12: 0,
        KEY_HOME: 0,
        KEY_INSERT: 0,
        KEY_PAGE_DOWN: 0,
        KEY_PAGE_UP: 0,
        KEY_PLUS: 0,
        KEY_MINUS: 0,
        KEY_QUOTATION: 0,
        KEY_SHIFT: 0,
        KEY_LEFT_SHIFT: 0,
        KEY_SPACE: 0,
        KEY_TAB: 0,
        KEY_TILDE: 0,
        KEY_ARROW_UP: 0,
        KEY_ARROW_DOWN: 0,
        KEY_ARROW_LEFT: 0,
        KEY_ARROW_RIGHT: 0,
        KEY_LEFT_BRACKET: 0,
        KEY_RIGHT_BRACKET: 0,
        KEY_SEMICOLON: 0,
        KEY_ASTERISK: 0
    },
    icons: {
        KEY_A: "T_A_Key_Dark.png",
        KEY_B: "T_B_Key_Dark.png",
        KEY_C: "T_C_Key_Dark.png",
        KEY_D: "T_D_Key_Dark.png",
        KEY_E: "T_E_Key_Dark.png",
        KEY_F: "T_F_Key_Dark.png",
        KEY_G: "T_G_Key_Dark.png",
        KEY_H: "T_H_Key_Dark.png",
        KEY_I: "T_I_Key_Dark.png",
        KEY_J: "T_J_Key_Dark.png",
        KEY_K: "T_K_Key_Dark.png",
        KEY_L: "T_L_Key_Dark.png",
        KEY_M: "T_M_Key_Dark.png",
        KEY_N: "T_N_Key_Dark.png",
        KEY_O: "T_O_Key_Dark.png",
        KEY_P: "T_P_Key_Dark.png",
        KEY_Q: "T_Q_Key_Dark.png",
        KEY_R: "T_R_Key_Dark.png",
        KEY_S: "T_S_Key_Dark.png",
        KEY_T: "T_T_Key_Dark.png",
        KEY_U: "T_U_Key_Dark.png",
        KEY_V: "T_V_Key_Dark.png",
        KEY_W: "T_W_Key_Dark.png",
        KEY_X: "T_X_Key_Dark.png",
        KEY_Y: "T_Y_Key_Dark.png",
        KEY_Z: "T_Z_Key_Dark.png",

        KEY_0: "T_0_Key_Dark.png",
        KEY_1: "T_1_Key_Dark.png",
        KEY_2: "T_2_Key_Dark.png",
        KEY_3: "T_3_Key_Dark.png",
        KEY_4: "T_4_Key_Dark.png",
        KEY_5: "T_5_Key_Dark.png",
        KEY_6: "T_6_Key_Dark.png",
        KEY_7: "T_7_Key_Dark.png",
        KEY_8: "T_8_Key_Dark.png",
        KEY_9: "T_9_Key_Dark.png",

        KEY_F1: "T_F1_Key_Dark.png",
        KEY_F2: "T_F2_Key_Dark.png",
        KEY_F3: "T_F3_Key_Dark.png",
        KEY_F4: "T_F4_Key_Dark.png",
        KEY_F5: "T_F5_Key_Dark.png",
        KEY_F6: "T_F6_Key_Dark.png",
        KEY_F7: "T_F7_Key_Dark.png",
        KEY_F8: "T_F8_Key_Dark.png",
        KEY_F9: "T_F9_Key_Dark.png",
        KEY_F10: "T_F10_Key_Dark.png",
        KEY_F11: "T_F11_Key_Dark.png",
        KEY_F12: "T_F12_Key_Dark.png",


        KEY_PAGE_DOWN: "T_PageDown_Key_Dark.png",
        KEY_PAGE_UP: "T_PageUp_Key_Dark.png",

        KEY_CTRL: "T_CTRL_Key_Dark.png",
        KEY_DEL: "T_DEL_Key_Dark.png",
        KEY_END: "T_END_Key_Dark.png",
        KEY_ENTER: "T_ENTER_Key_Dark.png",
        KEY_ESC: "T_ESC_Key_Dark.png",
        KEY_HOME: "T_HOME_Key_Dark.png",
        KEY_INSERT: "T_INSERT_Key_Dark.png",

        KEY_PLUS: "T_PLUS_Key_Dark.png",
        KEY_MINUS: "T_MINUS_Key_Dark.png",
        KEY_QUOTATION: "T_QUOTATION_Key_Dark.png",
        KEY_SHIFT: "T_SHIFT_Key_Dark.png",
        KEY_LEFT_SHIFT: "T_Shift_Super_Wide_Key_Dark.png",

        KEY_SPACE: "T_SPACE_Key_Dark.png",
        KEY_TAB: "T_TAB_Key_Dark.png",
        KEY_TILDE: "T_TILDE_Key_Dark.png",

        KEY_ARROW_UP: "T_Up_Key_Dark.png",
        KEY_ARROW_DOWN: "T_Down_Key_Dark.png",
        KEY_ARROW_LEFT: "T_Left_Key_Dark.png",
        KEY_ARROW_RIGHT: "T_Right_Key_Dark.png",

        KEY_LEFT_BRACKET: "T_Brackets_L_Key_Dark.png",
        KEY_RIGHT_BRACKET: "T_Brackets_R_Key_Dark.png",

        KEY_SEMICOLON: "T_Semicolon_Key_Dark.png",
        KEY_ASTERISK: "T_Asterisk_Key_Dark.png"
    },
    setting: {
    },
    default: {
    }
};

export default pad_unlicensedSNES;
