name: Bug Report
description: Create a report to help us improve
title: "[Bug] "
labels: ["Bug", "Triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Describe the steps to reproduce this bug. If applicable attach user/session data at the bottom
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen. If it is an existing move or ability
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: media
    attributes:
      label: Screenshots / Videos
      description:  If applicable, add screenshots or videos to help explain your problem.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: session-file
    attributes:
      label: Session export file
      description: Open Menu → ManageData → Export Session → Select slot. The file should now be in your `/Downloads` directory. Change the file extension type from `.prsv` to `.txt` (How to [Windows](https://www.guidingtech.com/how-to-change-file-type-on-windows/) | [Mac](https://support.apple.com/guide/mac-help/show-or-hide-filename-extensions-on-mac-mchlp2304/mac) | [iOS](https://www.guidingtech.com/change-file-type-extension-on-iphone/)).
      placeholder: Focus me and then drop your file here (or use the upload button at the bottom)
    validations:
      required: false
  - type: textarea
    id: data-file
    attributes:
      label: User data export file
      description: Open Menu → ManageData → Export Data. The file should now be in your `/Downloads` directory. Change the file extension type from `.prsv` to `.txt` (How to [Windows](https://www.guidingtech.com/how-to-change-file-type-on-windows/) | [Mac](https://support.apple.com/guide/mac-help/show-or-hide-filename-extensions-on-mac-mchlp2304/mac) | [iOS](https://www.guidingtech.com/change-file-type-extension-on-iphone/)).
      placeholder: Focus me and then drop your file here (or use the upload button at the bottom)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
