name: Feature Request
description: Suggest an idea for this project
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: relation
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: Clear and concise description of what the problem is.
      placeholder: E.g. "I'm always frustrated when [...]"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: description
    attributes:
      label: Describe the Feature
      description: A clear and concise description of what you want to happen. Add a link to the feature if it is an existing move/ability/etc.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
