name: Mystery Event
description: Propose a new mystery event
title: "[Event Proposal]: "
body:
  - type: dropdown
    id: rarity
    attributes:
      label: Rarity
      multiple: false
      options:
        - Common
        - Great
        - Ultra 
        - Rogue
        - Other (please specify)
    validations:
      required: true
  - type: input
    id: waves
    attributes:
      label: Waves
      placeholder: 1-200 (currently only 11-179 exist)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What is it?
      placeholder: Describe the event you are proposing
    validations:
      required: true
  - type: dropdown
    id: biomes
    attributes:
      label: Biomes
      multiple: true
      options:
        - any (no need to select all)
        - non-extreme (almost all except Space, Seabed, etc...)
        - TOWN
        - PLAINS
        - GRASS
        - TALL_GRASS
        - METROPOLIS
        - FOREST
        - SEA
        - SWAMP
        - BEACH
        - LAKE
        - SEABED
        - MOUNTAIN
        - BADLANDS
        - CAVE
        - DESERT
        - ICE_CAVE
        - MEADOW
        - POWER_PLANT
        - VOLCANO
        - GRAVEYARD
        - DOJO
        - FACTORY
        - RUINS
        - WASTELAND
        - ABYSS
        - SPACE
        - CONSTRUCTION_SITE
        - JUNGLE
        - FAIRY_CAVE
        - TEMPLE
        - SLUM
        - SNOWY_FOREST
        - ISLAND
        - LABORATORY
        - END
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: Options offered
      placeholder: Only four options can be displayed at a time
    validations:
      required: true
  - type: textarea
    id: design-notes
    attributes:
      label: Notes on Design
      placeholder: (If any needed)
    validations:
      required: false
  - type: textarea
    id: dev-notes
    attributes:
      label: Notes to Devs
      placeholder: (If any needed)
    validations:
      required: false
