name: Mystery Event
description: Propose a new mystery event
title: "[Event] "
labels: ["event proposal", "balance review"]
projects: ["AsdarDevelops/1"]
body:
  - type: input
    id: name
    attributes:
      label: Event Name
      description: Name of the event
      placeholder: e.g Fight or Flight
    validations:
      required: true
  - type: markdown # SEPARATOR
    attributes:
      value: |
        ---
  - type: dropdown
    id: rarity
    attributes:
      label: Rarity Tier
      description: Check out the [Event Proposal Guide](https://github.com/AsdarDevelops/PokeRogue-Events/blob/mystery-battle-events/MEs_Proposal_Guide.md#do-tiers-mean-anything) if you have not yet!
      multiple: false
      options:
        - Common
        - Great
        - Ultra
        - Rogue
        - Other or unsure (please specify)
    validations:
      required: true
  - type: markdown # SEPARATOR
    attributes:
      value: |
        ---
  - type: input
    id: waves
    attributes:
      label: Waves
      description: Classic/Challenge is 1 -200. Currently only 11-179 is supported.
      placeholder: 1-200
    validations:
      required: true
  - type: markdown # SEPARATOR
    attributes:
      value: |
        ---
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the event you are proposing
      placeholder: What is it?
    validations:
      required: true
  - type: markdown # SEPARATOR
    attributes:
      value: |
        ---
  - type: dropdown
    id: biomes
    attributes:
      label: Biomes
      description: Select all biomes where the event can occur
      multiple: true
      options:
        - ANY (no need to select all)
        - NON-EXTREME (almost all except Space, Seabed, etc...)
        - TOWN
        - PLAINS
        - GRASS
        - TALL_GRASS
        - METROPOLIS
        - FOREST
        - SEA
        - SWAMP
        - BEACH
        - LAKE
        - SEABED
        - MOUNTAIN
        - BADLANDS
        - CAVE
        - DESERT
        - ICE_CAVE
        - MEADOW
        - POWER_PLANT
        - VOLCANO
        - GRAVEYARD
        - DOJO
        - FACTORY
        - RUINS
        - WASTELAND
        - ABYSS
        - SPACE
        - CONSTRUCTION_SITE
        - JUNGLE
        - FAIRY_CAVE
        - TEMPLE
        - SLUM
        - SNOWY_FOREST
        - ISLAND
        - LABORATORY
        - END
        - OTHER (please specify)
    validations:
      required: true
  - type: markdown # SEPARATOR
    attributes:
      value: |
        ---
  - type: textarea
    id: options
    attributes:
      label: Options offered to the player
      description: A maximum of four options can be displayed at a time
      placeholder: Remember that only up to four options can be displayed at a time
      value: |
        - [ ] OPTION-1 Label
            - _OPTION-1 description._
        - [ ] OPTION-2 Label
            - _OPTION-2 description._
        - [ ] OPTION-3 Label
            - _OPTION-3 description._
        - [ ] OPTION-4 Label
            - _OPTION-4 description._
    validations:
      required: true
  - type: markdown # SEPARATOR
    attributes:
      value: |
        ---
  - type: textarea
    id: design-notes
    attributes:
      label: Explanation/Notes on Design
      description: Explain why you think this design is right and what this Event brings to the table
      placeholder: Explain why you think this design is right and what this Event brings to the table
    validations:
      required: true
  - type: markdown # SEPARATOR
    attributes:
      value: |
        ---
  - type: textarea
    id: dev-notes
    attributes:
      label: Notes to Developers
      placeholder: If necessary
    validations:
      required: false
