import type { SpeciesId } from "#enums/species-id";

export type StarterSpeciesId =
  | SpeciesId.BULBASAUR
  | SpeciesId.CHARMANDER
  | SpeciesId.SQUIRTLE
  | SpeciesId.CATERPIE
  | SpeciesId.WEEDLE
  | SpeciesId.PIDGEY
  | SpeciesId.RATTATA
  | SpeciesId.SPEAROW
  | SpeciesId.EKANS
  | SpeciesId.PIKACHU
  | SpeciesId.SANDSHREW
  | SpeciesId.NIDORAN_F
  | SpeciesId.NIDORAN_M
  | SpeciesId.VULPIX
  | SpeciesId.ZUBAT
  | SpeciesId.ODDISH
  | SpeciesId.PARAS
  | SpeciesId.VENONAT
  | SpeciesId.DIGLETT
  | SpeciesId.MEOWTH
  | SpeciesId.PSYDUCK
  | SpeciesId.MANKEY
  | SpeciesId.GROWLITHE
  | SpeciesId.POLIWAG
  | SpeciesId.ABRA
  | SpeciesId.MACHOP
  | SpeciesId.BELLSPROUT
  | SpeciesId.TENTACOOL
  | SpeciesId.GEODUDE
  | SpeciesId.PONYTA
  | SpeciesId.SLOWPOKE
  | SpeciesId.MAGNEMITE
  | SpeciesId.FARFETCHD
  | SpeciesId.DODUO
  | SpeciesId.SEEL
  | SpeciesId.GRIMER
  | SpeciesId.SHELLDER
  | SpeciesId.GASTLY
  | SpeciesId.ONIX
  | SpeciesId.DROWZEE
  | SpeciesId.KRABBY
  | SpeciesId.VOLTORB
  | SpeciesId.EXEGGCUTE
  | SpeciesId.CUBONE
  | SpeciesId.LICKITUNG
  | SpeciesId.KOFFING
  | SpeciesId.RHYHORN
  | SpeciesId.TANGELA
  | SpeciesId.KANGASKHAN
  | SpeciesId.HORSEA
  | SpeciesId.GOLDEEN
  | SpeciesId.STARYU
  | SpeciesId.SCYTHER
  | SpeciesId.PINSIR
  | SpeciesId.TAUROS
  | SpeciesId.MAGIKARP
  | SpeciesId.LAPRAS
  | SpeciesId.DITTO
  | SpeciesId.EEVEE
  | SpeciesId.PORYGON
  | SpeciesId.OMANYTE
  | SpeciesId.KABUTO
  | SpeciesId.AERODACTYL
  | SpeciesId.ARTICUNO
  | SpeciesId.ZAPDOS
  | SpeciesId.MOLTRES
  | SpeciesId.DRATINI
  | SpeciesId.MEWTWO
  | SpeciesId.MEW
  | SpeciesId.CHIKORITA
  | SpeciesId.CYNDAQUIL
  | SpeciesId.TOTODILE
  | SpeciesId.SENTRET
  | SpeciesId.HOOTHOOT
  | SpeciesId.LEDYBA
  | SpeciesId.SPINARAK
  | SpeciesId.CHINCHOU
  | SpeciesId.PICHU
  | SpeciesId.CLEFFA
  | SpeciesId.IGGLYBUFF
  | SpeciesId.TOGEPI
  | SpeciesId.NATU
  | SpeciesId.MAREEP
  | SpeciesId.HOPPIP
  | SpeciesId.AIPOM
  | SpeciesId.SUNKERN
  | SpeciesId.YANMA
  | SpeciesId.WOOPER
  | SpeciesId.MURKROW
  | SpeciesId.MISDREAVUS
  | SpeciesId.UNOWN
  | SpeciesId.GIRAFARIG
  | SpeciesId.PINECO
  | SpeciesId.DUNSPARCE
  | SpeciesId.GLIGAR
  | SpeciesId.SNUBBULL
  | SpeciesId.QWILFISH
  | SpeciesId.SHUCKLE
  | SpeciesId.HERACROSS
  | SpeciesId.SNEASEL
  | SpeciesId.TEDDIURSA
  | SpeciesId.SLUGMA
  | SpeciesId.SWINUB
  | SpeciesId.CORSOLA
  | SpeciesId.REMORAID
  | SpeciesId.DELIBIRD
  | SpeciesId.SKARMORY
  | SpeciesId.HOUNDOUR
  | SpeciesId.PHANPY
  | SpeciesId.STANTLER
  | SpeciesId.SMEARGLE
  | SpeciesId.TYROGUE
  | SpeciesId.SMOOCHUM
  | SpeciesId.ELEKID
  | SpeciesId.MAGBY
  | SpeciesId.MILTANK
  | SpeciesId.RAIKOU
  | SpeciesId.ENTEI
  | SpeciesId.SUICUNE
  | SpeciesId.LARVITAR
  | SpeciesId.LUGIA
  | SpeciesId.HO_OH
  | SpeciesId.CELEBI
  | SpeciesId.TREECKO
  | SpeciesId.TORCHIC
  | SpeciesId.MUDKIP
  | SpeciesId.POOCHYENA
  | SpeciesId.ZIGZAGOON
  | SpeciesId.WURMPLE
  | SpeciesId.LOTAD
  | SpeciesId.SEEDOT
  | SpeciesId.TAILLOW
  | SpeciesId.WINGULL
  | SpeciesId.RALTS
  | SpeciesId.SURSKIT
  | SpeciesId.SHROOMISH
  | SpeciesId.SLAKOTH
  | SpeciesId.NINCADA
  | SpeciesId.WHISMUR
  | SpeciesId.MAKUHITA
  | SpeciesId.AZURILL
  | SpeciesId.NOSEPASS
  | SpeciesId.SKITTY
  | SpeciesId.SABLEYE
  | SpeciesId.MAWILE
  | SpeciesId.ARON
  | SpeciesId.MEDITITE
  | SpeciesId.ELECTRIKE
  | SpeciesId.PLUSLE
  | SpeciesId.MINUN
  | SpeciesId.VOLBEAT
  | SpeciesId.ILLUMISE
  | SpeciesId.GULPIN
  | SpeciesId.CARVANHA
  | SpeciesId.WAILMER
  | SpeciesId.NUMEL
  | SpeciesId.TORKOAL
  | SpeciesId.SPOINK
  | SpeciesId.SPINDA
  | SpeciesId.TRAPINCH
  | SpeciesId.CACNEA
  | SpeciesId.SWABLU
  | SpeciesId.ZANGOOSE
  | SpeciesId.SEVIPER
  | SpeciesId.LUNATONE
  | SpeciesId.SOLROCK
  | SpeciesId.BARBOACH
  | SpeciesId.CORPHISH
  | SpeciesId.BALTOY
  | SpeciesId.LILEEP
  | SpeciesId.ANORITH
  | SpeciesId.FEEBAS
  | SpeciesId.CASTFORM
  | SpeciesId.KECLEON
  | SpeciesId.SHUPPET
  | SpeciesId.DUSKULL
  | SpeciesId.TROPIUS
  | SpeciesId.ABSOL
  | SpeciesId.WYNAUT
  | SpeciesId.SNORUNT
  | SpeciesId.SPHEAL
  | SpeciesId.CLAMPERL
  | SpeciesId.RELICANTH
  | SpeciesId.LUVDISC
  | SpeciesId.BAGON
  | SpeciesId.BELDUM
  | SpeciesId.REGIROCK
  | SpeciesId.REGICE
  | SpeciesId.REGISTEEL
  | SpeciesId.LATIAS
  | SpeciesId.LATIOS
  | SpeciesId.KYOGRE
  | SpeciesId.GROUDON
  | SpeciesId.RAYQUAZA
  | SpeciesId.JIRACHI
  | SpeciesId.DEOXYS
  | SpeciesId.TURTWIG
  | SpeciesId.CHIMCHAR
  | SpeciesId.PIPLUP
  | SpeciesId.STARLY
  | SpeciesId.BIDOOF
  | SpeciesId.KRICKETOT
  | SpeciesId.SHINX
  | SpeciesId.BUDEW
  | SpeciesId.CRANIDOS
  | SpeciesId.SHIELDON
  | SpeciesId.BURMY
  | SpeciesId.COMBEE
  | SpeciesId.PACHIRISU
  | SpeciesId.BUIZEL
  | SpeciesId.CHERUBI
  | SpeciesId.SHELLOS
  | SpeciesId.DRIFLOON
  | SpeciesId.BUNEARY
  | SpeciesId.GLAMEOW
  | SpeciesId.CHINGLING
  | SpeciesId.STUNKY
  | SpeciesId.BRONZOR
  | SpeciesId.BONSLY
  | SpeciesId.MIME_JR
  | SpeciesId.HAPPINY
  | SpeciesId.CHATOT
  | SpeciesId.SPIRITOMB
  | SpeciesId.GIBLE
  | SpeciesId.MUNCHLAX
  | SpeciesId.RIOLU
  | SpeciesId.HIPPOPOTAS
  | SpeciesId.SKORUPI
  | SpeciesId.CROAGUNK
  | SpeciesId.CARNIVINE
  | SpeciesId.FINNEON
  | SpeciesId.MANTYKE
  | SpeciesId.SNOVER
  | SpeciesId.ROTOM
  | SpeciesId.UXIE
  | SpeciesId.MESPRIT
  | SpeciesId.AZELF
  | SpeciesId.DIALGA
  | SpeciesId.PALKIA
  | SpeciesId.HEATRAN
  | SpeciesId.REGIGIGAS
  | SpeciesId.GIRATINA
  | SpeciesId.CRESSELIA
  | SpeciesId.PHIONE
  | SpeciesId.MANAPHY
  | SpeciesId.DARKRAI
  | SpeciesId.SHAYMIN
  | SpeciesId.ARCEUS
  | SpeciesId.VICTINI
  | SpeciesId.SNIVY
  | SpeciesId.TEPIG
  | SpeciesId.OSHAWOTT
  | SpeciesId.PATRAT
  | SpeciesId.LILLIPUP
  | SpeciesId.PURRLOIN
  | SpeciesId.PANSAGE
  | SpeciesId.PANSEAR
  | SpeciesId.PANPOUR
  | SpeciesId.MUNNA
  | SpeciesId.PIDOVE
  | SpeciesId.BLITZLE
  | SpeciesId.ROGGENROLA
  | SpeciesId.WOOBAT
  | SpeciesId.DRILBUR
  | SpeciesId.AUDINO
  | SpeciesId.TIMBURR
  | SpeciesId.TYMPOLE
  | SpeciesId.THROH
  | SpeciesId.SAWK
  | SpeciesId.SEWADDLE
  | SpeciesId.VENIPEDE
  | SpeciesId.COTTONEE
  | SpeciesId.PETILIL
  | SpeciesId.BASCULIN
  | SpeciesId.SANDILE
  | SpeciesId.DARUMAKA
  | SpeciesId.MARACTUS
  | SpeciesId.DWEBBLE
  | SpeciesId.SCRAGGY
  | SpeciesId.SIGILYPH
  | SpeciesId.YAMASK
  | SpeciesId.TIRTOUGA
  | SpeciesId.ARCHEN
  | SpeciesId.TRUBBISH
  | SpeciesId.ZORUA
  | SpeciesId.MINCCINO
  | SpeciesId.GOTHITA
  | SpeciesId.SOLOSIS
  | SpeciesId.DUCKLETT
  | SpeciesId.VANILLITE
  | SpeciesId.DEERLING
  | SpeciesId.EMOLGA
  | SpeciesId.KARRABLAST
  | SpeciesId.FOONGUS
  | SpeciesId.FRILLISH
  | SpeciesId.ALOMOMOLA
  | SpeciesId.JOLTIK
  | SpeciesId.FERROSEED
  | SpeciesId.KLINK
  | SpeciesId.TYNAMO
  | SpeciesId.ELGYEM
  | SpeciesId.LITWICK
  | SpeciesId.AXEW
  | SpeciesId.CUBCHOO
  | SpeciesId.CRYOGONAL
  | SpeciesId.SHELMET
  | SpeciesId.STUNFISK
  | SpeciesId.MIENFOO
  | SpeciesId.DRUDDIGON
  | SpeciesId.GOLETT
  | SpeciesId.PAWNIARD
  | SpeciesId.BOUFFALANT
  | SpeciesId.RUFFLET
  | SpeciesId.VULLABY
  | SpeciesId.HEATMOR
  | SpeciesId.DURANT
  | SpeciesId.DEINO
  | SpeciesId.LARVESTA
  | SpeciesId.COBALION
  | SpeciesId.TERRAKION
  | SpeciesId.VIRIZION
  | SpeciesId.TORNADUS
  | SpeciesId.THUNDURUS
  | SpeciesId.RESHIRAM
  | SpeciesId.ZEKROM
  | SpeciesId.LANDORUS
  | SpeciesId.KYUREM
  | SpeciesId.KELDEO
  | SpeciesId.MELOETTA
  | SpeciesId.GENESECT
  | SpeciesId.CHESPIN
  | SpeciesId.FENNEKIN
  | SpeciesId.FROAKIE
  | SpeciesId.BUNNELBY
  | SpeciesId.FLETCHLING
  | SpeciesId.SCATTERBUG
  | SpeciesId.LITLEO
  | SpeciesId.FLABEBE
  | SpeciesId.SKIDDO
  | SpeciesId.PANCHAM
  | SpeciesId.FURFROU
  | SpeciesId.ESPURR
  | SpeciesId.HONEDGE
  | SpeciesId.SPRITZEE
  | SpeciesId.SWIRLIX
  | SpeciesId.INKAY
  | SpeciesId.BINACLE
  | SpeciesId.SKRELP
  | SpeciesId.CLAUNCHER
  | SpeciesId.HELIOPTILE
  | SpeciesId.TYRUNT
  | SpeciesId.AMAURA
  | SpeciesId.HAWLUCHA
  | SpeciesId.DEDENNE
  | SpeciesId.CARBINK
  | SpeciesId.GOOMY
  | SpeciesId.KLEFKI
  | SpeciesId.PHANTUMP
  | SpeciesId.PUMPKABOO
  | SpeciesId.BERGMITE
  | SpeciesId.NOIBAT
  | SpeciesId.XERNEAS
  | SpeciesId.YVELTAL
  | SpeciesId.ZYGARDE
  | SpeciesId.DIANCIE
  | SpeciesId.HOOPA
  | SpeciesId.VOLCANION
  | SpeciesId.ROWLET
  | SpeciesId.LITTEN
  | SpeciesId.POPPLIO
  | SpeciesId.PIKIPEK
  | SpeciesId.YUNGOOS
  | SpeciesId.GRUBBIN
  | SpeciesId.CRABRAWLER
  | SpeciesId.ORICORIO
  | SpeciesId.CUTIEFLY
  | SpeciesId.ROCKRUFF
  | SpeciesId.WISHIWASHI
  | SpeciesId.MAREANIE
  | SpeciesId.MUDBRAY
  | SpeciesId.DEWPIDER
  | SpeciesId.FOMANTIS
  | SpeciesId.MORELULL
  | SpeciesId.SALANDIT
  | SpeciesId.STUFFUL
  | SpeciesId.BOUNSWEET
  | SpeciesId.COMFEY
  | SpeciesId.ORANGURU
  | SpeciesId.PASSIMIAN
  | SpeciesId.WIMPOD
  | SpeciesId.SANDYGAST
  | SpeciesId.PYUKUMUKU
  | SpeciesId.TYPE_NULL
  | SpeciesId.MINIOR
  | SpeciesId.KOMALA
  | SpeciesId.TURTONATOR
  | SpeciesId.TOGEDEMARU
  | SpeciesId.MIMIKYU
  | SpeciesId.BRUXISH
  | SpeciesId.DRAMPA
  | SpeciesId.DHELMISE
  | SpeciesId.JANGMO_O
  | SpeciesId.TAPU_KOKO
  | SpeciesId.TAPU_LELE
  | SpeciesId.TAPU_BULU
  | SpeciesId.TAPU_FINI
  | SpeciesId.COSMOG
  | SpeciesId.NIHILEGO
  | SpeciesId.BUZZWOLE
  | SpeciesId.PHEROMOSA
  | SpeciesId.XURKITREE
  | SpeciesId.CELESTEELA
  | SpeciesId.KARTANA
  | SpeciesId.GUZZLORD
  | SpeciesId.NECROZMA
  | SpeciesId.MAGEARNA
  | SpeciesId.MARSHADOW
  | SpeciesId.POIPOLE
  | SpeciesId.STAKATAKA
  | SpeciesId.BLACEPHALON
  | SpeciesId.ZERAORA
  | SpeciesId.MELTAN
  | SpeciesId.GROOKEY
  | SpeciesId.SCORBUNNY
  | SpeciesId.SOBBLE
  | SpeciesId.SKWOVET
  | SpeciesId.ROOKIDEE
  | SpeciesId.BLIPBUG
  | SpeciesId.NICKIT
  | SpeciesId.GOSSIFLEUR
  | SpeciesId.WOOLOO
  | SpeciesId.CHEWTLE
  | SpeciesId.YAMPER
  | SpeciesId.ROLYCOLY
  | SpeciesId.APPLIN
  | SpeciesId.SILICOBRA
  | SpeciesId.CRAMORANT
  | SpeciesId.ARROKUDA
  | SpeciesId.TOXEL
  | SpeciesId.SIZZLIPEDE
  | SpeciesId.CLOBBOPUS
  | SpeciesId.SINISTEA
  | SpeciesId.HATENNA
  | SpeciesId.IMPIDIMP
  | SpeciesId.MILCERY
  | SpeciesId.FALINKS
  | SpeciesId.PINCURCHIN
  | SpeciesId.SNOM
  | SpeciesId.STONJOURNER
  | SpeciesId.EISCUE
  | SpeciesId.INDEEDEE
  | SpeciesId.MORPEKO
  | SpeciesId.CUFANT
  | SpeciesId.DRACOZOLT
  | SpeciesId.ARCTOZOLT
  | SpeciesId.DRACOVISH
  | SpeciesId.ARCTOVISH
  | SpeciesId.DURALUDON
  | SpeciesId.DREEPY
  | SpeciesId.ZACIAN
  | SpeciesId.ZAMAZENTA
  | SpeciesId.ETERNATUS
  | SpeciesId.KUBFU
  | SpeciesId.ZARUDE
  | SpeciesId.REGIELEKI
  | SpeciesId.REGIDRAGO
  | SpeciesId.GLASTRIER
  | SpeciesId.SPECTRIER
  | SpeciesId.CALYREX
  | SpeciesId.ENAMORUS
  | SpeciesId.SPRIGATITO
  | SpeciesId.FUECOCO
  | SpeciesId.QUAXLY
  | SpeciesId.LECHONK
  | SpeciesId.TAROUNTULA
  | SpeciesId.NYMBLE
  | SpeciesId.PAWMI
  | SpeciesId.TANDEMAUS
  | SpeciesId.FIDOUGH
  | SpeciesId.SMOLIV
  | SpeciesId.SQUAWKABILLY
  | SpeciesId.NACLI
  | SpeciesId.CHARCADET
  | SpeciesId.TADBULB
  | SpeciesId.WATTREL
  | SpeciesId.MASCHIFF
  | SpeciesId.SHROODLE
  | SpeciesId.BRAMBLIN
  | SpeciesId.TOEDSCOOL
  | SpeciesId.KLAWF
  | SpeciesId.CAPSAKID
  | SpeciesId.RELLOR
  | SpeciesId.FLITTLE
  | SpeciesId.TINKATINK
  | SpeciesId.WIGLETT
  | SpeciesId.BOMBIRDIER
  | SpeciesId.FINIZEN
  | SpeciesId.VAROOM
  | SpeciesId.CYCLIZAR
  | SpeciesId.ORTHWORM
  | SpeciesId.GLIMMET
  | SpeciesId.GREAVARD
  | SpeciesId.FLAMIGO
  | SpeciesId.CETODDLE
  | SpeciesId.VELUZA
  | SpeciesId.DONDOZO
  | SpeciesId.TATSUGIRI
  | SpeciesId.GREAT_TUSK
  | SpeciesId.SCREAM_TAIL
  | SpeciesId.BRUTE_BONNET
  | SpeciesId.FLUTTER_MANE
  | SpeciesId.SLITHER_WING
  | SpeciesId.SANDY_SHOCKS
  | SpeciesId.IRON_TREADS
  | SpeciesId.IRON_BUNDLE
  | SpeciesId.IRON_HANDS
  | SpeciesId.IRON_JUGULIS
  | SpeciesId.IRON_MOTH
  | SpeciesId.IRON_THORNS
  | SpeciesId.FRIGIBAX
  | SpeciesId.GIMMIGHOUL
  | SpeciesId.WO_CHIEN
  | SpeciesId.CHIEN_PAO
  | SpeciesId.TING_LU
  | SpeciesId.CHI_YU
  | SpeciesId.ROARING_MOON
  | SpeciesId.IRON_VALIANT
  | SpeciesId.KORAIDON
  | SpeciesId.MIRAIDON
  | SpeciesId.WALKING_WAKE
  | SpeciesId.IRON_LEAVES
  | SpeciesId.POLTCHAGEIST
  | SpeciesId.OKIDOGI
  | SpeciesId.MUNKIDORI
  | SpeciesId.FEZANDIPITI
  | SpeciesId.OGERPON
  | SpeciesId.GOUGING_FIRE
  | SpeciesId.RAGING_BOLT
  | SpeciesId.IRON_BOULDER
  | SpeciesId.IRON_CROWN
  | SpeciesId.TERAPAGOS
  | SpeciesId.PECHARUNT
  | SpeciesId.ALOLA_RATTATA
  | SpeciesId.ALOLA_SANDSHREW
  | SpeciesId.ALOLA_VULPIX
  | SpeciesId.ALOLA_DIGLETT
  | SpeciesId.ALOLA_MEOWTH
  | SpeciesId.ALOLA_GEODUDE
  | SpeciesId.ALOLA_GRIMER
  | SpeciesId.BATTLE_BOND_GRENINJA
  | SpeciesId.ETERNAL_FLOETTE
  | SpeciesId.GALAR_MEOWTH
  | SpeciesId.GALAR_PONYTA
  | SpeciesId.GALAR_SLOWPOKE
  | SpeciesId.GALAR_FARFETCHD
  | SpeciesId.GALAR_ARTICUNO
  | SpeciesId.GALAR_ZAPDOS
  | SpeciesId.GALAR_MOLTRES
  | SpeciesId.GALAR_CORSOLA
  | SpeciesId.GALAR_ZIGZAGOON
  | SpeciesId.GALAR_DARUMAKA
  | SpeciesId.GALAR_YAMASK
  | SpeciesId.GALAR_STUNFISK
  | SpeciesId.HISUI_GROWLITHE
  | SpeciesId.HISUI_VOLTORB
  | SpeciesId.HISUI_QWILFISH
  | SpeciesId.HISUI_SNEASEL
  | SpeciesId.HISUI_BASCULIN
  | SpeciesId.HISUI_ZORUA
  | SpeciesId.PALDEA_TAUROS
  | SpeciesId.PALDEA_WOOPER
  | SpeciesId.BLOODMOON_URSALUNA;
