name: "Setup pnpm and Node.js, and install dependencies"
description: |
  Sets up pnpm and Node.js environment for workflows and installs dependencies.
  Requires the repo to be cloned to at least have `pnpm-lock.yaml` and `package.json`

runs:
  using: "composite"
  steps:
    - name: Install pnpm, Node.js and dependencies
      uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # 2.1.0
      with:
        runtime: node@24.9
        install: true
        require-lockfile: true
        cache: true
