//! DO NOT EDIT THIS FILE - CREATED BY THE `eggMoves:parse` script automatically
import { MoveId } from "#enums/move-id";
import { SpeciesId } from "#enums/species-id";

/**
 * An object mapping all base form {@linkcode SpeciesId}s to an array of {@linkcode MoveId}s corresponding
 * to their current egg moves.
 * Generated by the `eggMoves:parse` script using a CSV sourced from the current Balance Team spreadsheet.
 */
export const speciesEggMoves = "{{table}}";
