version = 1

# From Nintendo for black and white
[[annotations]]
path = [
    "cry/*",              # All pokemon cries are from showdown, which sources them from nintendo
]
SPDX-FileCopyrightText = "Nintendo, Creatures Inc., GAME FREAK inc."
SPDX-License-Identifier = "LicenseRef-FAIR-USE"


# Audio assets known to come from pokemon reborn
[[annotations]]
path = ["battle_anims/PRSFX-*.wav"]
SPDX-FileCopyrightText = "The Pokemon Reborn Team https://www.rebornevo.com/pr/index.html/"
SPDX-License-Identifier = "LicsenseRef-POKEMON-REBORN"

# Firel
[[annotations]]
path = [
    "bgm/abyss.mp3",
    "bgm/desert.mp3",
    "bgm/end.mp3",
    "bgm/graveyard.mp3",
    "bgm/ice_cave.mp3",
    "bgm/laboratory.mp3",
    "bgm/metropolis.mp3",
    "bgm/mystery_encounter_delibirdy.mp3",
    "bgm/plains.mp3",
    "bgm/power_plant.mp3",
    "bgm/seabed.mp3",
    "bgm/space.mp3",
    "bgm/title.mp3",
    "bgm/volcano.mp3",
]
SPDX-FileCopyrightText = "Firel"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"

# LMZ
[[annotations]]
path = ["bgm/jungle.mp3", "bgm/lake.mp3", "bgm/ruins.mp3"]
SPDX-FileCopyrightText = "Lmz"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"

# Andr06
[[annotations]]
path = [
    "bgm/forest.mp3",
    "bgm/fairy_cave.mp3",
    "bgm/sea.mp3",
    "bgm/slum.mp3",
    "bgm/title_afd.mp3",
    "bgm/battle_rival_3_afd.mp3",
]
SPDX-FileCopyrightText = "Andr06"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"

# Leavannite
[[annotations]]
path = ["bgm/wasteland.mp3"]
SPDX-FileCopyrightText = "Leavannite"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"


# Audio assets sampled from royalty-free sites like pixabay and findsounds and modified or otherwise edited
# Public domain (aka CC0-1.0)
[[annotations]]
path = [
    "se/gacha_dial.wav",
    "se/gacha_dispense.wav",
    "se/gacha_running.wav",
    "se/upgrade.wav",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
