#!/bin/sh

# Adjust the grep pattern to include .js, .jsx, .ts, and .tsx files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(jsx?|tsx?)$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "Validating Javascript and TypeScript:\n"

for FILE in $STAGED_FILES
do
  # Attempt to fix issues automatically
  npx eslint --fix "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "ESLint Passed: $FILE"
  else
    echo "ESLint Failed: $FILE"
    PASS=false
  fi
done

echo "Javascript and TypeScript validation completed!\n"

if ! $PASS; then
  echo "COMMIT FAILED: Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again."
  exit 1
else
  echo "COMMIT SUCCEEDED"
fi

exit $?
