
export const allDefaultBgmAssets: Map<string, string | undefined> = new Map<string, string | undefined>([
  ["menu", undefined],
  ["level_up_fanfare", "bw/level_up_fanfare.mp3"],
  ["level_up_fanfare", "bw/level_up_fanfare.mp3"],
  ["item_fanfare", "bw/item_fanfare.mp3"],
  ["minor_fanfare", "bw/minor_fanfare.mp3"],
  ["heal", "bw/heal.mp3"],
  ["victory_trainer", "bw/victory_trainer.mp3"],
  ["victory_team_plasma", "bw/victory_team_plasma.mp3"],
  ["victory_gym", "bw/victory_gym.mp3"],
  ["victory_champion", "bw/victory_champion.mp3"],
  ["evolution", "bw/evolution.mp3"],
  ["evolution_fanfare", "bw/evolution_fanfare.mp3"]
]);

export const allDefaultSeAssets: Map<string, string | undefined> = new Map<string, string | undefined>([
  ["select", "ui"],
  ["menu_open", "ui"],
  ["error", "ui"],
  ["hit", undefined],
  ["hit_strong", undefined],
  ["hit_weak", undefined],
  ["stat_up", undefined],
  ["stat_down", undefined],
  ["faint", undefined],
  ["flee", undefined],
  ["low_hp", undefined],
  ["exp", undefined],
  ["level_up", undefined],
  ["sparkle", undefined],
  ["restore", undefined],
  ["shine", undefined],
  ["shing", undefined],
  ["charge", undefined],
  ["beam", undefined],
  ["upgrade", undefined],
  ["buy", undefined],
  ["achv", undefined],

  ["pb_rel", undefined],
  ["pb_throw", undefined],
  ["pb_bounce_1", undefined],
  ["pb_bounce_2", undefined],
  ["pb_move", undefined],
  ["pb_catch", undefined],
  ["pb_lock", undefined],

  ["pb_tray_enter", undefined],
  ["pb_tray_ball", undefined],
  ["pb_tray_empty", undefined],

  ["egg_crack", undefined],
  ["egg_hatch", undefined],
  ["gacha_dial", undefined],
  ["gacha_running", undefined],
  ["gacha_dispense", undefined],

  ["PRSFX- Transform", "battle_anims"]
]);

export const allDefaultImageAssets: Map<string, string | string[]> = new Map<string, string | string[]>([
  ["loading_bg", "arenas"],
  ["logo", ""],
  ["candy", "ui"],
  ["candy_overlay", "ui"],
  ["cursor", "ui"],
  ["cursor_reverse", "ui"],
  ["pbinfo_player", "ui"],
  ["pbinfo_player_stats", "ui"],
  ["pbinfo_player_mini", "ui"],
  ["pbinfo_player_mini_stats", "ui"],
  ["pbinfo_enemy_mini", "ui"],
  ["pbinfo_enemy_mini_stats", "ui"],
  ["pbinfo_enemy_boss", "ui"],
  ["pbinfo_enemy_boss_stats", "ui"],
  ["overlay_lv", "ui"],
  ["overlay_exp", "ui"],
  ["icon_owned", "ui"],
  ["icon_egg_move", "ui"],
  ["ability_bar_left", "ui"],
  ["bgm_bar", "ui"],
  ["party_exp_bar", "ui"],
  ["achv_bar", "ui"],
  ["achv_bar_2", "ui"],
  ["achv_bar_3", "ui"],
  ["achv_bar_4", "ui"],
  ["achv_bar_5", "ui"],
  ["shiny_star", ["ui", "shiny.png"]],
  ["shiny_star_1", ["ui", "shiny_1.png"]],
  ["shiny_star_2", ["ui", "shiny_2.png"]],
  ["shiny_star_small", ["ui", "shiny_small.png"]],
  ["shiny_star_small_1", ["ui", "shiny_small_1.png"]],
  ["shiny_star_small_2", ["ui", "shiny_small_2.png"]],
  ["favorite", ["ui", "favorite.png"]],
  ["passive_bg", ["ui", "passive_bg.png"]],
  ["ha_capsule", ["ui", "ha_capsule.png"]],
  ["champion_ribbon", ["ui", "champion_ribbon.png"]],
  ["icon_spliced", "ui"],
  ["icon_lock", ["ui", "icon_lock.png"]],
  ["icon_stop", ["ui", "icon_stop.png"]],
  ["icon_tera", "ui"],
  ["type_tera", "ui"],
  ["dawn_icon_fg", "ui"],
  ["dawn_icon_mg", "ui"],
  ["dawn_icon_bg", "ui"],
  ["day_icon_fg", "ui"],
  ["day_icon_mg", "ui"],
  ["day_icon_bg", "ui"],
  ["dusk_icon_fg", "ui"],
  ["dusk_icon_mg", "ui"],
  ["dusk_icon_bg", "ui"],
  ["night_icon_fg", "ui"],
  ["night_icon_mg", "ui"],
  ["night_icon_bg", "ui"],
  ["pb_tray_overlay_player", "ui"],
  ["pb_tray_overlay_enemy", "ui"],
  ["party_bg", "ui"],
  ["party_bg_double", "ui"],
  ["party_slot_overlay_lv", "ui"],
  ["party_slot_hp_bar", "ui"],
  ["summary_bg", "ui"],
  ["summary_overlay_shiny", "ui"],
  ["summary_profile", "ui"],
  ["summary_profile_prompt_z", "ui"],      // The pixel Z button prompt
  ["summary_profile_prompt_a", "ui"],     // The pixel A button prompt
  ["summary_profile_ability", "ui"],      // Pixel text 'ABILITY'
  ["summary_profile_passive", "ui"],      // Pixel text 'PASSIVE'
  ["summary_status", "ui"],
  ["summary_stats", "ui"],
  ["summary_stats_overlay_exp", "ui"],
  ["summary_moves", "ui"],
  ["summary_moves_effect", "ui"],
  ["summary_moves_overlay_row", "ui"],
  ["summary_moves_overlay_pp", "ui"],
  ["scroll_bar", "ui"],
  ["scroll_bar_handle", "ui"],
  ["starter_container_bg", "ui"],
  ["starter_select_bg", "ui"],
  ["select_cursor", "ui"],
  ["select_cursor_highlight", "ui"],
  ["select_cursor_highlight_thick", "ui"],
  ["select_cursor_pokerus", "ui"],
  ["select_gen_cursor", "ui"],
  ["select_gen_cursor_highlight", "ui"],
  ["saving_icon", "ui"],
  ["discord", "ui"],
  ["google", "ui"],
  ["settings_icon", "ui"],
  ["default_bg", "arenas"],
  ["pkmn__back__sub", ["pokemon/back", "sub.png"]],
  ["pkmn__sub", ["pokemon", "sub.png"]],
  ["tera", "effects"],
  ["evo_sparkle", "effects"],
  ["gacha_glass", "egg"],
  ["gacha_eggs", "egg"],
  ["gacha_knob", "egg"],
  ["egg_list_bg", "ui"],
  ["egg_summary_bg", "ui"],
  ["end_m", "cg"],
  ["end_f", "cg"],
  ["encounter_radar", "mystery-encounters"],
]);

export const allDefaultAtlasAssets: Map<string, string | string[]> = new Map<string, string | string[]>([
  ["bg", "ui"],
  ["prompt", "ui"],
  ["namebox", "ui"],
  ["pbinfo_player_type", "ui"],
  ["pbinfo_player_type1", "ui"],
  ["pbinfo_player_type2", "ui"],
  ["pbinfo_enemy_type", "ui"],
  ["pbinfo_enemy_type1", "ui"],
  ["pbinfo_enemy_type2", "ui"],
  ["pbinfo_stat", "ui"],
  ["pbinfo_stat_numbers", "ui"],
  ["numbers", "ui"],
  ["numbers_red", "ui"],
  ["overlay_hp", "ui"],
  ["overlay_hp_boss", "ui"],
  ["shiny_icons", "ui"],
  ["type_bgs", "ui"],
  ["pb_tray_ball", "ui"],
  ["party_slot_main", "ui"],
  ["party_slot", "ui"],
  ["party_slot_hp_overlay", "ui"],
  ["party_pb", "ui"],
  ["party_cancel", "ui"],
  ["summary_moves_cursor", "ui"],
  // Load character sprites
  ["trainer_m_back", "trainer"],
  ["trainer_m_back_pb", "trainer"],
  ["trainer_f_back", "trainer"],
  ["trainer_f_back_pb", "trainer"],
  ["c_rival_m", ["character", "rival_m"]],
  ["c_rival_f", ["character", "rival_f"]],
  // Load pokemon-related images
  ["battle_stats", "effects"],
  ["shiny", "effects"],
  ["shiny_2", "effects"],
  ["shiny_3", "effects"],
  ["pb_particles", "effects"],
  ["tera_sparkle", "effects"],
  ["pb", ""],
  ["items", ""],
  ["types", ""],
  ["statuses", ""],
  ["categories", ""],
  ["egg", "egg"],
  ["egg_crack", "egg"],
  ["egg_icons", "egg"],
  ["egg_shard", "egg"],
  ["egg_lightrays", "egg"],
  ["gacha_hatch", "egg"],
  ["dualshock", "inputs"],
  ["xbox", "inputs"],
  ["keyboard", "inputs"],
]);
