import { Type } from './type'

export enum MOVE_CATEGORY {
  PHYSICAL = 0,
  SPECIAL,
  STATUS
};

export default class Move {
  public id: integer;
  public name: string;
  public type: integer;
  public category: integer;
  public power: integer;
  public accuracy: integer;
  public pp: integer;
  public tm: string;
  public effect: string;
  public chance: integer;
  public generation: integer;

  constructor(id, name, type, category, power, accuracy, pp, tm, effect, chance, generation) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.category = category;
    this.power = power;
    this.accuracy = accuracy;
    this.pp = pp;
    this.tm = tm;
    this.effect = effect;
    this.chance = chance;
    this.generation = generation;
  }
}

export enum Moves {
  POUND = 1,
  KARATE_CHOP,
  DOUBLE_SLAP,
  COMET_PUNCH,
  MEGA_PUNCH,
  PAY_DAY,
  FIRE_PUNCH,
  ICE_PUNCH,
  THUNDER_PUNCH,
  SCRATCH,
  VISE_GRIP,
  GUILLOTINE,
  RAZOR_WIND,
  SWORDS_DANCE,
  CUT,
  GUST,
  WING_ATTACK,
  WHIRLWIND,
  FLY,
  BIND,
  SLAM,
  VINE_WHIP,
  STOMP,
  DOUBLE_KICK,
  MEGA_KICK,
  JUMP_KICK,
  ROLLING_KICK,
  SAND_ATTACK,
  HEADBUTT,
  HORN_ATTACK,
  FURY_ATTACK,
  HORN_DRILL,
  TACKLE,
  BODY_SLAM,
  WRAP,
  TAKE_DOWN,
  THRASH,
  DOUBLE_EDGE,
  TAIL_WHIP,
  POISON_STING,
  TWINEEDLE,
  PIN_MISSILE,
  LEER,
  BITE,
  GROWL,
  ROAR,
  SING,
  SUPERSONIC,
  SONIC_BOOM,
  DISABLE,
  ACID,
  EMBER,
  FLAMETHROWER,
  MIST,
  WATER_GUN,
  HYDRO_PUMP,
  SURF,
  ICE_BEAM,
  BLIZZARD,
  PSYBEAM,
  BUBBLE_BEAM,
  AURORA_BEAM,
  HYPER_BEAM,
  PECK,
  DRILL_PECK,
  SUBMISSION,
  LOW_KICK,
  COUNTER,
  SEISMIC_TOSS,
  STRENGTH,
  ABSORB,
  MEGA_DRAIN,
  LEECH_SEED,
  GROWTH,
  RAZOR_LEAF,
  SOLAR_BEAM,
  POISON_POWDER,
  STUN_SPORE,
  SLEEP_POWDER,
  PETAL_DANCE,
  STRING_SHOT,
  DRAGON_RAGE,
  FIRE_SPIN,
  THUNDER_SHOCK,
  THUNDERBOLT,
  THUNDER_WAVE,
  THUNDER,
  ROCK_THROW,
  EARTHQUAKE,
  FISSURE,
  DIG,
  TOXIC,
  CONFUSION,
  PSYCHIC,
  HYPNOSIS,
  MEDITATE,
  AGILITY,
  QUICK_ATTACK,
  RAGE,
  TELEPORT,
  NIGHT_SHADE,
  MIMIC,
  SCREECH,
  DOUBLE_TEAM,
  RECOVER,
  HARDEN,
  MINIMIZE,
  SMOKESCREEN,
  CONFUSE_RAY,
  WITHDRAW,
  DEFENSE_CURL,
  BARRIER,
  LIGHT_SCREEN,
  HAZE,
  REFLECT,
  FOCUS_ENERGY,
  BIDE,
  METRONOME,
  MIRROR_MOVE,
  SELF_DESTRUCT,
  EGG_BOMB,
  LICK,
  SMOG,
  SLUDGE,
  BONE_CLUB,
  FIRE_BLAST,
  WATERFALL,
  CLAMP,
  SWIFT,
  SKULL_BASH,
  SPIKE_CANNON,
  CONSTRICT,
  AMNESIA,
  KINESIS,
  SOFT_BOILED,
  HIGH_JUMP_KICK,
  GLARE,
  DREAM_EATER,
  POISON_GAS,
  BARRAGE,
  LEECH_LIFE,
  LOVELY_KISS,
  SKY_ATTACK,
  TRANSFORM,
  BUBBLE,
  DIZZY_PUNCH,
  SPORE,
  FLASH,
  PSYWAVE,
  SPLASH,
  ACID_ARMOR,
  CRABHAMMER,
  EXPLOSION,
  FURY_SWIPES,
  BONEMERANG,
  REST,
  ROCK_SLIDE,
  HYPER_FANG,
  SHARPEN,
  CONVERSION,
  TRI_ATTACK,
  SUPER_FANG,
  SLASH,
  SUBSTITUTE,
  STRUGGLE,
  SKETCH,
  TRIPLE_KICK,
  THIEF,
  SPIDER_WEB,
  MIND_READER,
  NIGHTMARE,
  FLAME_WHEEL,
  SNORE,
  CURSE,
  FLAIL,
  CONVERSION_2,
  AEROBLAST,
  COTTON_SPORE,
  REVERSAL,
  SPITE,
  POWDER_SNOW,
  PROTECT,
  MACH_PUNCH,
  SCARY_FACE,
  FEINT_ATTACK,
  SWEET_KISS,
  BELLY_DRUM,
  SLUDGE_BOMB,
  MUD_SLAP,
  OCTAZOOKA,
  SPIKES,
  ZAP_CANNON,
  FORESIGHT,
  DESTINY_BOND,
  PERISH_SONG,
  ICY_WIND,
  DETECT,
  BONE_RUSH,
  LOCK_ON,
  OUTRAGE,
  SANDSTORM,
  GIGA_DRAIN,
  ENDURE,
  CHARM,
  ROLLOUT,
  FALSE_SWIPE,
  SWAGGER,
  MILK_DRINK,
  SPARK,
  FURY_CUTTER,
  STEEL_WING,
  MEAN_LOOK,
  ATTRACT,
  SLEEP_TALK,
  HEAL_BELL,
  RETURN,
  PRESENT,
  FRUSTRATION,
  SAFEGUARD,
  PAIN_SPLIT,
  SACRED_FIRE,
  MAGNITUDE,
  DYNAMIC_PUNCH,
  MEGAHORN,
  DRAGON_BREATH,
  BATON_PASS,
  ENCORE,
  PURSUIT,
  RAPID_SPIN,
  SWEET_SCENT,
  IRON_TAIL,
  METAL_CLAW,
  VITAL_THROW,
  MORNING_SUN,
  SYNTHESIS,
  MOONLIGHT,
  HIDDEN_POWER,
  CROSS_CHOP,
  TWISTER,
  RAIN_DANCE,
  SUNNY_DAY,
  CRUNCH,
  MIRROR_COAT,
  PSYCH_UP,
  EXTREME_SPEED,
  ANCIENT_POWER,
  SHADOW_BALL,
  FUTURE_SIGHT,
  ROCK_SMASH,
  WHIRLPOOL,
  BEAT_UP,
  FAKE_OUT,
  UPROAR,
  STOCKPILE,
  SPIT_UP,
  SWALLOW,
  HEAT_WAVE,
  HAIL,
  TORMENT,
  FLATTER,
  WILL_O_WISP,
  MEMENTO,
  FACADE,
  FOCUS_PUNCH,
  SMELLING_SALTS,
  FOLLOW_ME,
  NATURE_POWER,
  CHARGE,
  TAUNT,
  HELPING_HAND,
  TRICK,
  ROLE_PLAY,
  WISH,
  ASSIST,
  INGRAIN,
  SUPERPOWER,
  MAGIC_COAT,
  RECYCLE,
  REVENGE,
  BRICK_BREAK,
  YAWN,
  KNOCK_OFF,
  ENDEAVOR,
  ERUPTION,
  SKILL_SWAP,
  IMPRISON,
  REFRESH,
  GRUDGE,
  SNATCH,
  SECRET_POWER,
  DIVE,
  ARM_THRUST,
  CAMOUFLAGE,
  TAIL_GLOW,
  LUSTER_PURGE,
  MIST_BALL,
  FEATHER_DANCE,
  TEETER_DANCE,
  BLAZE_KICK,
  MUD_SPORT,
  ICE_BALL,
  NEEDLE_ARM,
  SLACK_OFF,
  HYPER_VOICE,
  POISON_FANG,
  CRUSH_CLAW,
  BLAST_BURN,
  HYDRO_CANNON,
  METEOR_MASH,
  ASTONISH,
  WEATHER_BALL,
  AROMATHERAPY,
  FAKE_TEARS,
  AIR_CUTTER,
  OVERHEAT,
  ODOR_SLEUTH,
  ROCK_TOMB,
  SILVER_WIND,
  METAL_SOUND,
  GRASS_WHISTLE,
  TICKLE,
  COSMIC_POWER,
  WATER_SPOUT,
  SIGNAL_BEAM,
  SHADOW_PUNCH,
  EXTRASENSORY,
  SKY_UPPERCUT,
  SAND_TOMB,
  SHEER_COLD,
  MUDDY_WATER,
  BULLET_SEED,
  AERIAL_ACE,
  ICICLE_SPEAR,
  IRON_DEFENSE,
  BLOCK,
  HOWL,
  DRAGON_CLAW,
  FRENZY_PLANT,
  BULK_UP,
  BOUNCE,
  MUD_SHOT,
  POISON_TAIL,
  COVET,
  VOLT_TACKLE,
  MAGICAL_LEAF,
  WATER_SPORT,
  CALM_MIND,
  LEAF_BLADE,
  DRAGON_DANCE,
  ROCK_BLAST,
  SHOCK_WAVE,
  WATER_PULSE,
  DOOM_DESIRE,
  PSYCHO_BOOST,
  ROOST,
  GRAVITY,
  MIRACLE_EYE,
  WAKE_UP_SLAP,
  HAMMER_ARM,
  GYRO_BALL,
  HEALING_WISH,
  BRINE,
  NATURAL_GIFT,
  FEINT,
  PLUCK,
  TAILWIND,
  ACUPRESSURE,
  METAL_BURST,
  U_TURN,
  CLOSE_COMBAT,
  PAYBACK,
  ASSURANCE,
  EMBARGO,
  FLING,
  PSYCHO_SHIFT,
  TRUMP_CARD,
  HEAL_BLOCK,
  WRING_OUT,
  POWER_TRICK,
  GASTRO_ACID,
  LUCKY_CHANT,
  ME_FIRST,
  COPYCAT,
  POWER_SWAP,
  GUARD_SWAP,
  PUNISHMENT,
  LAST_RESORT,
  WORRY_SEED,
  SUCKER_PUNCH,
  TOXIC_SPIKES,
  HEART_SWAP,
  AQUA_RING,
  MAGNET_RISE,
  FLARE_BLITZ,
  FORCE_PALM,
  AURA_SPHERE,
  ROCK_POLISH,
  POISON_JAB,
  DARK_PULSE,
  NIGHT_SLASH,
  AQUA_TAIL,
  SEED_BOMB,
  AIR_SLASH,
  X_SCISSOR,
  BUG_BUZZ,
  DRAGON_PULSE,
  DRAGON_RUSH,
  POWER_GEM,
  DRAIN_PUNCH,
  VACUUM_WAVE,
  FOCUS_BLAST,
  ENERGY_BALL,
  BRAVE_BIRD,
  EARTH_POWER,
  SWITCHEROO,
  GIGA_IMPACT,
  NASTY_PLOT,
  BULLET_PUNCH,
  AVALANCHE,
  ICE_SHARD,
  SHADOW_CLAW,
  THUNDER_FANG,
  ICE_FANG,
  FIRE_FANG,
  SHADOW_SNEAK,
  MUD_BOMB,
  PSYCHO_CUT,
  ZEN_HEADBUTT,
  MIRROR_SHOT,
  FLASH_CANNON,
  ROCK_CLIMB,
  DEFOG,
  TRICK_ROOM,
  DRACO_METEOR,
  DISCHARGE,
  LAVA_PLUME,
  LEAF_STORM,
  POWER_WHIP,
  ROCK_WRECKER,
  CROSS_POISON,
  GUNK_SHOT,
  IRON_HEAD,
  MAGNET_BOMB,
  STONE_EDGE,
  CAPTIVATE,
  STEALTH_ROCK,
  GRASS_KNOT,
  CHATTER,
  JUDGMENT,
  BUG_BITE,
  CHARGE_BEAM,
  WOOD_HAMMER,
  AQUA_JET,
  ATTACK_ORDER,
  DEFEND_ORDER,
  HEAL_ORDER,
  HEAD_SMASH,
  DOUBLE_HIT,
  ROAR_OF_TIME,
  SPACIAL_REND,
  LUNAR_DANCE,
  CRUSH_GRIP,
  MAGMA_STORM,
  DARK_VOID,
  SEED_FLARE,
  OMINOUS_WIND,
  SHADOW_FORCE,
  HONE_CLAWS,
  WIDE_GUARD,
  GUARD_SPLIT,
  POWER_SPLIT,
  WONDER_ROOM,
  PSYSHOCK,
  VENOSHOCK,
  AUTOTOMIZE,
  RAGE_POWDER,
  TELEKINESIS,
  MAGIC_ROOM,
  SMACK_DOWN,
  STORM_THROW,
  FLAME_BURST,
  SLUDGE_WAVE,
  QUIVER_DANCE,
  HEAVY_SLAM,
  SYNCHRONOISE,
  ELECTRO_BALL,
  SOAK,
  FLAME_CHARGE,
  COIL,
  LOW_SWEEP,
  ACID_SPRAY,
  FOUL_PLAY,
  SIMPLE_BEAM,
  ENTRAINMENT,
  AFTER_YOU,
  ROUND,
  ECHOED_VOICE,
  CHIP_AWAY,
  CLEAR_SMOG,
  STORED_POWER,
  QUICK_GUARD,
  ALLY_SWITCH,
  SCALD,
  SHELL_SMASH,
  HEAL_PULSE,
  HEX,
  SKY_DROP,
  SHIFT_GEAR,
  CIRCLE_THROW,
  INCINERATE,
  QUASH,
  ACROBATICS,
  REFLECT_TYPE,
  RETALIATE,
  FINAL_GAMBIT,
  BESTOW,
  INFERNO,
  WATER_PLEDGE,
  FIRE_PLEDGE,
  GRASS_PLEDGE,
  VOLT_SWITCH,
  STRUGGLE_BUG,
  BULLDOZE,
  FROST_BREATH,
  DRAGON_TAIL,
  WORK_UP,
  ELECTROWEB,
  WILD_CHARGE,
  DRILL_RUN,
  DUAL_CHOP,
  HEART_STAMP,
  HORN_LEECH,
  SACRED_SWORD,
  RAZOR_SHELL,
  HEAT_CRASH,
  LEAF_TORNADO,
  STEAMROLLER,
  COTTON_GUARD,
  NIGHT_DAZE,
  PSYSTRIKE,
  TAIL_SLAP,
  HURRICANE,
  HEAD_CHARGE,
  GEAR_GRIND,
  SEARING_SHOT,
  TECHNO_BLAST,
  RELIC_SONG,
  SECRET_SWORD,
  GLACIATE,
  BOLT_STRIKE,
  BLUE_FLARE,
  FIERY_DANCE,
  FREEZE_SHOCK,
  ICE_BURN,
  SNARL,
  ICICLE_CRASH,
  V_CREATE,
  FUSION_FLARE,
  FUSION_BOLT
};

export const allMoves = [
  [ Moves.POUND, "Pound", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 40, 100, 35, "", "", -1, 1 ],
  [ Moves.KARATE_CHOP, "Karate Chop", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 50, 100, 25, "", "High critical hit ratio.", -1, 1 ],
  [ Moves.DOUBLE_SLAP, "Double Slap", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 15, 85, 10, "", "Hits 2-5 times in one turn.", -1, 1 ],
  [ Moves.COMET_PUNCH, "Comet Punch", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 18, 85, 15, "", "Hits 2-5 times in one turn.", -1, 1 ],
  [ Moves.MEGA_PUNCH, "Mega Punch", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 80, 85, 20, "", "", -1, 1 ],
  [ Moves.PAY_DAY, "Pay Day", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 40, 100, 20, "", "Money is earned after the battle.", -1, 1 ],
  [ Moves.FIRE_PUNCH, "Fire Punch", Type.FIRE, MOVE_CATEGORY.PHYSICAL, 75, 100, 15, "TM67", "May burn opponent.", 10, 1 ],
  [ Moves.ICE_PUNCH, "Ice Punch", Type.ICE, MOVE_CATEGORY.PHYSICAL, 75, 100, 15, "TM69", "May freeze opponent.", 10, 1 ],
  [ Moves.THUNDER_PUNCH, "Thunder Punch", Type.ELECTRIC, MOVE_CATEGORY.PHYSICAL, 75, 100, 15, "TM68", "May paralyze opponent.", 10, 1 ],
  [ Moves.SCRATCH, "Scratch", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 40, 100, 35, "", "", -1, 1 ],
  [ Moves.VISE_GRIP, "Vise Grip", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 55, 100, 30, "", "", -1, 1 ],
  [ Moves.GUILLOTINE, "Guillotine", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, -1, 30, 5, "", "One-Hit-KO, if it hits.", -1, 1 ],
  [ Moves.RAZOR_WIND, "Razor Wind", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 80, 100, 10, "", "Charges on first turn, attacks on second. High critical hit ratio.", -1, 1 ],
  [ Moves.SWORDS_DANCE, "Swords Dance", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "TM88", "Sharply raises user's Attack.", -1, 1 ],
  [ Moves.CUT, "Cut", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 50, 95, 30, "", "", -1, 1 ],
  [ Moves.GUST, "Gust", Type.FLYING, MOVE_CATEGORY.SPECIAL, 40, 100, 35, "", "Hits Pokémon using Fly/Bounce/Sky Drop with double power.", -1, 1 ],
  [ Moves.WING_ATTACK, "Wing Attack", Type.FLYING, MOVE_CATEGORY.PHYSICAL, 60, 100, 35, "", "", -1, 1 ],
  [ Moves.WHIRLWIND, "Whirlwind", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "In battles, the opponent switches. In the wild, the Pokémon runs.", -1, 1 ],
  [ Moves.FLY, "Fly", Type.FLYING, MOVE_CATEGORY.PHYSICAL, 90, 95, 15, "TM97", "Flies up on first turn, attacks on second turn.", -1, 1 ],
  [ Moves.BIND, "Bind", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 15, 85, 20, "", "Traps opponent, damaging them for 4-5 turns.", 100, 1 ],
  [ Moves.SLAM, "Slam", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 80, 75, 20, "", "", -1, 1 ],
  [ Moves.VINE_WHIP, "Vine Whip", Type.GRASS, MOVE_CATEGORY.PHYSICAL, 45, 100, 25, "", "", -1, 1 ],
  [ Moves.STOMP, "Stomp", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 65, 100, 20, "", "May cause flinching.", 30, 1 ],
  [ Moves.DOUBLE_KICK, "Double Kick", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 30, 100, 30, "", "Hits twice in one turn.", -1, 1 ],
  [ Moves.MEGA_KICK, "Mega Kick", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 120, 75, 5, "", "", -1, 1 ],
  [ Moves.JUMP_KICK, "Jump Kick", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 100, 95, 10, "", "If it misses, the user loses half their HP.", -1, 1 ],
  [ Moves.ROLLING_KICK, "Rolling Kick", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 60, 85, 15, "", "May cause flinching.", 30, 1 ],
  [ Moves.SAND_ATTACK, "Sand Attack", Type.GROUND, MOVE_CATEGORY.STATUS, -1, 100, 15, "", "Lowers opponent's Accuracy.", -1, 1 ],
  [ Moves.HEADBUTT, "Headbutt", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 70, 100, 15, "", "May cause flinching.", 30, 1 ],
  [ Moves.HORN_ATTACK, "Horn Attack", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 65, 100, 25, "", "", -1, 1 ],
  [ Moves.FURY_ATTACK, "Fury Attack", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 15, 85, 20, "", "Hits 2-5 times in one turn.", -1, 1 ],
  [ Moves.HORN_DRILL, "Horn Drill", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, -1, 30, 5, "", "One-Hit-KO, if it hits.", -1, 1 ],
  [ Moves.TACKLE, "Tackle", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 40, 100, 35, "", "", -1, 1 ],
  [ Moves.BODY_SLAM, "Body Slam", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 85, 100, 15, "TM66", "May paralyze opponent.", 30, 1 ],
  [ Moves.WRAP, "Wrap", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 15, 90, 20, "", "Traps opponent, damaging them for 4-5 turns.", 100, 1 ],
  [ Moves.TAKE_DOWN, "Take Down", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 90, 85, 20, "TM01", "User receives recoil damage.", -1, 1 ],
  [ Moves.THRASH, "Thrash", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 120, 100, 10, "", "User attacks for 2-3 turns but then becomes confused.", -1, 1 ],
  [ Moves.DOUBLE_EDGE, "Double-Edge", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 120, 100, 15, "", "User receives recoil damage.", -1, 1 ],
  [ Moves.TAIL_WHIP, "Tail Whip", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 30, "", "Lowers opponent's Defense.", -1, 1 ],
  [ Moves.POISON_STING, "Poison Sting", Type.POISON, MOVE_CATEGORY.PHYSICAL, 15, 100, 35, "", "May poison the opponent.", 30, 1 ],
  [ Moves.TWINEEDLE, "Twineedle", Type.BUG, MOVE_CATEGORY.PHYSICAL, 25, 100, 20, "", "Hits twice in one turn. May poison opponent.", 20, 1 ],
  [ Moves.PIN_MISSILE, "Pin Missile", Type.BUG, MOVE_CATEGORY.PHYSICAL, 25, 95, 20, "", "Hits 2-5 times in one turn.", -1, 1 ],
  [ Moves.LEER, "Leer", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 30, "", "Lowers opponent's Defense.", 100, 1 ],
  [ Moves.BITE, "Bite", Type.DARK, MOVE_CATEGORY.PHYSICAL, 60, 100, 25, "", "May cause flinching.", 30, 1 ],
  [ Moves.GROWL, "Growl", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 40, "", "Lowers opponent's Attack.", -1, 1 ],
  [ Moves.ROAR, "Roar", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "In battles, the opponent switches. In the wild, the Pokémon runs.", -1, 1 ],
  [ Moves.SING, "Sing", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 55, 15, "", "Puts opponent to sleep.", -1, 1 ],
  [ Moves.SUPERSONIC, "Supersonic", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 55, 20, "", "Confuses opponent.", -1, 1 ],
  [ Moves.SONIC_BOOM, "Sonic Boom", Type.NORMAL, MOVE_CATEGORY.SPECIAL, -1, 90, 20, "", "Always inflicts 20 HP.", -1, 1 ],
  [ Moves.DISABLE, "Disable", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 20, "", "Opponent can't use its last attack for a few turns.", -1, 1 ],
  [ Moves.ACID, "Acid", Type.POISON, MOVE_CATEGORY.SPECIAL, 40, 100, 30, "", "May lower opponent's Special Defense.", 10, 1 ],
  [ Moves.EMBER, "Ember", Type.FIRE, MOVE_CATEGORY.SPECIAL, 40, 100, 25, "", "May burn opponent.", 10, 1 ],
  [ Moves.FLAMETHROWER, "Flamethrower", Type.FIRE, MOVE_CATEGORY.SPECIAL, 90, 100, 15, "TM125", "May burn opponent.", 10, 1 ],
  [ Moves.MIST, "Mist", Type.ICE, MOVE_CATEGORY.STATUS, -1, -1, 30, "", "User's stats cannot be changed for a period of time.", -1, 1 ],
  [ Moves.WATER_GUN, "Water Gun", Type.WATER, MOVE_CATEGORY.SPECIAL, 40, 100, 25, "", "", -1, 1 ],
  [ Moves.HYDRO_PUMP, "Hydro Pump", Type.WATER, MOVE_CATEGORY.SPECIAL, 110, 80, 5, "TM142", "", -1, 1 ],
  [ Moves.SURF, "Surf", Type.WATER, MOVE_CATEGORY.SPECIAL, 90, 100, 15, "TM123", "Hits all adjacent Pokémon.", -1, 1 ],
  [ Moves.ICE_BEAM, "Ice Beam", Type.ICE, MOVE_CATEGORY.SPECIAL, 90, 100, 10, "TM135", "May freeze opponent.", 10, 1 ],
  [ Moves.BLIZZARD, "Blizzard", Type.ICE, MOVE_CATEGORY.SPECIAL, 110, 70, 5, "TM143", "May freeze opponent.", 10, 1 ],
  [ Moves.PSYBEAM, "Psybeam", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 65, 100, 20, "TM16", "May confuse opponent.", 10, 1 ],
  [ Moves.BUBBLE_BEAM, "Bubble Beam", Type.WATER, MOVE_CATEGORY.SPECIAL, 65, 100, 20, "", "May lower opponent's Speed.", 10, 1 ],
  [ Moves.AURORA_BEAM, "Aurora Beam", Type.ICE, MOVE_CATEGORY.SPECIAL, 65, 100, 20, "", "May lower opponent's Attack.", 10, 1 ],
  [ Moves.HYPER_BEAM, "Hyper Beam", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 150, 90, 5, "TM163", "User must recharge next turn.", -1, 1 ],
  [ Moves.PECK, "Peck", Type.FLYING, MOVE_CATEGORY.PHYSICAL, 35, 100, 35, "", "", -1, 1 ],
  [ Moves.DRILL_PECK, "Drill Peck", Type.FLYING, MOVE_CATEGORY.PHYSICAL, 80, 100, 20, "", "", -1, 1 ],
  [ Moves.SUBMISSION, "Submission", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 80, 80, 20, "", "User receives recoil damage.", -1, 1 ],
  [ Moves.LOW_KICK, "Low Kick", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, -1, 100, 20, "TM12", "The heavier the opponent, the stronger the attack.", -1, 1 ],
  [ Moves.COUNTER, "Counter", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, -1, 100, 20, "", "When hit by a Physical Attack, user strikes back with 2x power.", -1, 1 ],
  [ Moves.SEISMIC_TOSS, "Seismic Toss", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, -1, 100, 20, "", "Inflicts damage equal to user's level.", -1, 1 ],
  [ Moves.STRENGTH, "Strength", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 80, 100, 15, "", "", -1, 1 ],
  [ Moves.ABSORB, "Absorb", Type.GRASS, MOVE_CATEGORY.SPECIAL, 20, 100, 25, "", "User recovers half the HP inflicted on opponent.", -1, 1 ],
  [ Moves.MEGA_DRAIN, "Mega Drain", Type.GRASS, MOVE_CATEGORY.SPECIAL, 40, 100, 15, "", "User recovers half the HP inflicted on opponent.", -1, 1 ],
  [ Moves.LEECH_SEED, "Leech Seed", Type.GRASS, MOVE_CATEGORY.STATUS, -1, 90, 10, "", "Drains HP from opponent each turn.", -1, 1 ],
  [ Moves.GROWTH, "Growth", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Raises user's Attack and Special Attack.", -1, 1 ],
  [ Moves.RAZOR_LEAF, "Razor Leaf", Type.GRASS, MOVE_CATEGORY.PHYSICAL, 55, 95, 25, "", "High critical hit ratio.", -1, 1 ],
  [ Moves.SOLAR_BEAM, "Solar Beam", Type.GRASS, MOVE_CATEGORY.SPECIAL, 120, 100, 10, "TM168", "Charges on first turn, attacks on second.", -1, 1 ],
  [ Moves.POISON_POWDER, "Poison Powder", Type.POISON, MOVE_CATEGORY.STATUS, -1, 75, 35, "", "Poisons opponent.", -1, 1 ],
  [ Moves.STUN_SPORE, "Stun Spore", Type.GRASS, MOVE_CATEGORY.STATUS, -1, 75, 30, "", "Paralyzes opponent.", -1, 1 ],
  [ Moves.SLEEP_POWDER, "Sleep Powder", Type.GRASS, MOVE_CATEGORY.STATUS, -1, 75, 15, "", "Puts opponent to sleep.", -1, 1 ],
  [ Moves.PETAL_DANCE, "Petal Dance", Type.GRASS, MOVE_CATEGORY.SPECIAL, 120, 100, 10, "", "User attacks for 2-3 turns but then becomes confused.", -1, 1 ],
  [ Moves.STRING_SHOT, "String Shot", Type.BUG, MOVE_CATEGORY.STATUS, -1, 95, 40, "", "Sharply lowers opponent's Speed.", -1, 1 ],
  [ Moves.DRAGON_RAGE, "Dragon Rage", Type.DRAGON, MOVE_CATEGORY.SPECIAL, -1, 100, 10, "", "Always inflicts 40 HP.", -1, 1 ],
  [ Moves.FIRE_SPIN, "Fire Spin", Type.FIRE, MOVE_CATEGORY.SPECIAL, 35, 85, 15, "TM24", "Traps opponent, damaging them for 4-5 turns.", 100, 1 ],
  [ Moves.THUNDER_SHOCK, "Thunder Shock", Type.ELECTRIC, MOVE_CATEGORY.SPECIAL, 40, 100, 30, "", "May paralyze opponent.", 10, 1 ],
  [ Moves.THUNDERBOLT, "Thunderbolt", Type.ELECTRIC, MOVE_CATEGORY.SPECIAL, 90, 100, 15, "TM126", "May paralyze opponent.", 10, 1 ],
  [ Moves.THUNDER_WAVE, "Thunder Wave", Type.ELECTRIC, MOVE_CATEGORY.STATUS, -1, 90, 20, "TM82", "Paralyzes opponent.", -1, 1 ],
  [ Moves.THUNDER, "Thunder", Type.ELECTRIC, MOVE_CATEGORY.SPECIAL, 110, 70, 10, "TM166", "May paralyze opponent.", 30, 1 ],
  [ Moves.ROCK_THROW, "Rock Throw", Type.ROCK, MOVE_CATEGORY.PHYSICAL, 50, 90, 15, "", "", -1, 1 ],
  [ Moves.EARTHQUAKE, "Earthquake", Type.GROUND, MOVE_CATEGORY.PHYSICAL, 100, 100, 10, "TM149", "Power is doubled if opponent is underground from using Dig.", -1, 1 ],
  [ Moves.FISSURE, "Fissure", Type.GROUND, MOVE_CATEGORY.PHYSICAL, -1, 30, 5, "", "One-Hit-KO, if it hits.", -1, 1 ],
  [ Moves.DIG, "Dig", Type.GROUND, MOVE_CATEGORY.PHYSICAL, 80, 100, 10, "TM55", "Digs underground on first turn, attacks on second. Can also escape from caves.", -1, 1 ],
  [ Moves.TOXIC, "Toxic", Type.POISON, MOVE_CATEGORY.STATUS, -1, 90, 10, "", "Badly poisons opponent.", -1, 1 ],
  [ Moves.CONFUSION, "Confusion", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 50, 100, 25, "", "May confuse opponent.", 10, 1 ],
  [ Moves.PSYCHIC, "Psychic", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 90, 100, 10, "TM120", "May lower opponent's Special Defense.", 10, 1 ],
  [ Moves.HYPNOSIS, "Hypnosis", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, 60, 20, "", "Puts opponent to sleep.", -1, 1 ],
  [ Moves.MEDITATE, "Meditate", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 40, "", "Raises user's Attack.", -1, 1 ],
  [ Moves.AGILITY, "Agility", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 30, "TM04", "Sharply raises user's Speed.", -1, 1 ],
  [ Moves.QUICK_ATTACK, "Quick Attack", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 40, 100, 30, "", "User attacks first.", -1, 1 ],
  [ Moves.RAGE, "Rage", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 20, 100, 20, "", "Raises user's Attack when hit.", -1, 1 ],
  [ Moves.TELEPORT, "Teleport", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Allows user to flee wild battles; also warps player to last PokéCenter.", -1, 1 ],
  [ Moves.NIGHT_SHADE, "Night Shade", Type.GHOST, MOVE_CATEGORY.SPECIAL, -1, 100, 15, "TM42", "Inflicts damage equal to user's level.", -1, 1 ],
  [ Moves.MIMIC, "Mimic", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Copies the opponent's last move.", -1, 1 ],
  [ Moves.SCREECH, "Screech", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 85, 40, "", "Sharply lowers opponent's Defense.", -1, 1 ],
  [ Moves.DOUBLE_TEAM, "Double Team", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "Raises user's Evasiveness.", -1, 1 ],
  [ Moves.RECOVER, "Recover", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "User recovers half its max HP.", -1, 1 ],
  [ Moves.HARDEN, "Harden", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 30, "", "Raises user's Defense.", -1, 1 ],
  [ Moves.MINIMIZE, "Minimize", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Sharply raises user's Evasiveness.", -1, 1 ],
  [ Moves.SMOKESCREEN, "Smokescreen", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 20, "", "Lowers opponent's Accuracy.", -1, 1 ],
  [ Moves.CONFUSE_RAY, "Confuse Ray", Type.GHOST, MOVE_CATEGORY.STATUS, -1, 100, 10, "TM17", "Confuses opponent.", -1, 1 ],
  [ Moves.WITHDRAW, "Withdraw", Type.WATER, MOVE_CATEGORY.STATUS, -1, -1, 40, "", "Raises user's Defense.", -1, 1 ],
  [ Moves.DEFENSE_CURL, "Defense Curl", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 40, "", "Raises user's Defense.", -1, 1 ],
  [ Moves.BARRIER, "Barrier", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Sharply raises user's Defense.", -1, 1 ],
  [ Moves.LIGHT_SCREEN, "Light Screen", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 30, "TM75", "Halves damage from Special attacks for 5 turns.", -1, 1 ],
  [ Moves.HAZE, "Haze", Type.ICE, MOVE_CATEGORY.STATUS, -1, -1, 30, "", "Resets all stat changes.", -1, 1 ],
  [ Moves.REFLECT, "Reflect", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 20, "TM74", "Halves damage from Physical attacks for 5 turns.", -1, 1 ],
  [ Moves.FOCUS_ENERGY, "Focus Energy", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 30, "", "Increases critical hit ratio.", -1, 1 ],
  [ Moves.BIDE, "Bide", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, -1, -1, 10, "", "User takes damage for two turns then strikes back double.", -1, 1 ],
  [ Moves.METRONOME, "Metronome", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "TM80", "User performs almost any move in the game at random.", -1, 1 ],
  [ Moves.MIRROR_MOVE, "Mirror Move", Type.FLYING, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "User performs the opponent's last move.", -1, 1 ],
  [ Moves.SELF_DESTRUCT, "Self-Destruct", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 200, 100, 5, "", "User faints.", -1, 1 ],
  [ Moves.EGG_BOMB, "Egg Bomb", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 100, 75, 10, "", "", -1, 1 ],
  [ Moves.LICK, "Lick", Type.GHOST, MOVE_CATEGORY.PHYSICAL, 30, 100, 30, "", "May paralyze opponent.", 30, 1 ],
  [ Moves.SMOG, "Smog", Type.POISON, MOVE_CATEGORY.SPECIAL, 30, 70, 20, "", "May poison opponent.", 40, 1 ],
  [ Moves.SLUDGE, "Sludge", Type.POISON, MOVE_CATEGORY.SPECIAL, 65, 100, 20, "", "May poison opponent.", 30, 1 ],
  [ Moves.BONE_CLUB, "Bone Club", Type.GROUND, MOVE_CATEGORY.PHYSICAL, 65, 85, 20, "", "May cause flinching.", 10, 1 ],
  [ Moves.FIRE_BLAST, "Fire Blast", Type.FIRE, MOVE_CATEGORY.SPECIAL, 110, 85, 5, "TM141", "May burn opponent.", 10, 1 ],
  [ Moves.WATERFALL, "Waterfall", Type.WATER, MOVE_CATEGORY.PHYSICAL, 80, 100, 15, "TM77", "May cause flinching.", 20, 1 ],
  [ Moves.CLAMP, "Clamp", Type.WATER, MOVE_CATEGORY.PHYSICAL, 35, 85, 15, "", "Traps opponent, damaging them for 4-5 turns.", 100, 1 ],
  [ Moves.SWIFT, "Swift", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 60, 999, 20, "TM32", "Ignores Accuracy and Evasiveness.", -1, 1 ],
  [ Moves.SKULL_BASH, "Skull Bash", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 130, 100, 10, "", "Raises Defense on first turn, attacks on second.", 100, 1 ],
  [ Moves.SPIKE_CANNON, "Spike Cannon", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 20, 100, 15, "", "Hits 2-5 times in one turn.", -1, 1 ],
  [ Moves.CONSTRICT, "Constrict", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 10, 100, 35, "", "May lower opponent's Speed by one stage.", 10, 1 ],
  [ Moves.AMNESIA, "Amnesia", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 20, "TM128", "Sharply raises user's Special Defense.", -1, 1 ],
  [ Moves.KINESIS, "Kinesis", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, 80, 15, "", "Lowers opponent's Accuracy.", -1, 1 ],
  [ Moves.SOFT_BOILED, "Soft-Boiled", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "User recovers half its max HP.", -1, 1 ],
  [ Moves.HIGH_JUMP_KICK, "High Jump Kick", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 130, 90, 10, "", "If it misses, the user loses half their HP.", -1, 1 ],
  [ Moves.GLARE, "Glare", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 30, "", "Paralyzes opponent.", -1, 1 ],
  [ Moves.DREAM_EATER, "Dream Eater", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 100, 100, 15, "", "User recovers half the HP inflicted on a sleeping opponent.", -1, 1 ],
  [ Moves.POISON_GAS, "Poison Gas", Type.POISON, MOVE_CATEGORY.STATUS, -1, 90, 40, "", "Poisons opponent.", -1, 1 ],
  [ Moves.BARRAGE, "Barrage", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 15, 85, 20, "", "Hits 2-5 times in one turn.", -1, 1 ],
  [ Moves.LEECH_LIFE, "Leech Life", Type.BUG, MOVE_CATEGORY.PHYSICAL, 80, 100, 10, "TM95", "User recovers half the HP inflicted on opponent.", -1, 1 ],
  [ Moves.LOVELY_KISS, "Lovely Kiss", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 75, 10, "", "Puts opponent to sleep.", -1, 1 ],
  [ Moves.SKY_ATTACK, "Sky Attack", Type.FLYING, MOVE_CATEGORY.PHYSICAL, 140, 90, 5, "", "Charges on first turn, attacks on second. May cause flinching. High critical hit ratio.", 30, 1 ],
  [ Moves.TRANSFORM, "Transform", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "User takes on the form and attacks of the opponent.", -1, 1 ],
  [ Moves.BUBBLE, "Bubble", Type.WATER, MOVE_CATEGORY.SPECIAL, 40, 100, 30, "", "May lower opponent's Speed.", 10, 1 ],
  [ Moves.DIZZY_PUNCH, "Dizzy Punch", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 70, 100, 10, "", "May confuse opponent.", 20, 1 ],
  [ Moves.SPORE, "Spore", Type.GRASS, MOVE_CATEGORY.STATUS, -1, 100, 15, "", "Puts opponent to sleep.", -1, 1 ],
  [ Moves.FLASH, "Flash", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 20, "", "Lowers opponent's Accuracy.", -1, 1 ],
  [ Moves.PSYWAVE, "Psywave", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, -1, 100, 15, "", "Inflicts damage 50-150% of user's level.", -1, 1 ],
  [ Moves.SPLASH, "Splash", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 40, "", "Doesn't do ANYTHING.", -1, 1 ],
  [ Moves.ACID_ARMOR, "Acid Armor", Type.POISON, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Sharply raises user's Defense.", -1, 1 ],
  [ Moves.CRABHAMMER, "Crabhammer", Type.WATER, MOVE_CATEGORY.PHYSICAL, 100, 90, 10, "", "High critical hit ratio.", -1, 1 ],
  [ Moves.EXPLOSION, "Explosion", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 250, 100, 5, "", "User faints.", -1, 1 ],
  [ Moves.FURY_SWIPES, "Fury Swipes", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 18, 80, 15, "", "Hits 2-5 times in one turn.", -1, 1 ],
  [ Moves.BONEMERANG, "Bonemerang", Type.GROUND, MOVE_CATEGORY.PHYSICAL, 50, 90, 10, "", "Hits twice in one turn.", -1, 1 ],
  [ Moves.REST, "Rest", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 5, "TM85", "User sleeps for 2 turns, but user is fully healed.", -1, 1 ],
  [ Moves.ROCK_SLIDE, "Rock Slide", Type.ROCK, MOVE_CATEGORY.PHYSICAL, 75, 90, 10, "TM86", "May cause flinching.", 30, 1 ],
  [ Moves.HYPER_FANG, "Hyper Fang", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 80, 90, 15, "", "May cause flinching.", 10, 1 ],
  [ Moves.SHARPEN, "Sharpen", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 30, "", "Raises user's Attack.", -1, 1 ],
  [ Moves.CONVERSION, "Conversion", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 30, "", "Changes user's type to that of its first move.", -1, 1 ],
  [ Moves.TRI_ATTACK, "Tri Attack", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 80, 100, 10, "", "May paralyze, burn or freeze opponent.", 20, 1 ],
  [ Moves.SUPER_FANG, "Super Fang", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, -1, 90, 10, "", "Always takes off half of the opponent's HP.", -1, 1 ],
  [ Moves.SLASH, "Slash", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 70, 100, 20, "", "High critical hit ratio.", -1, 1 ],
  [ Moves.SUBSTITUTE, "Substitute", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "TM103", "Uses HP to creates a decoy that takes hits.", -1, 1 ],
  [ Moves.STRUGGLE, "Struggle", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 50, -1, -1, "", "Only usable when all PP are gone. Hurts the user.", -1, 1 ],
  [ Moves.SKETCH, "Sketch", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 1, "", "Permanently copies the opponent's last move.", -1, 2 ],
  [ Moves.TRIPLE_KICK, "Triple Kick", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 10, 90, 10, "", "Hits thrice in one turn at increasing power.", -1, 2 ],
  [ Moves.THIEF, "Thief", Type.DARK, MOVE_CATEGORY.PHYSICAL, 60, 100, 25, "TM18", "Also steals opponent's held item.", -1, 2 ],
  [ Moves.SPIDER_WEB, "Spider Web", Type.BUG, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Opponent cannot escape/switch.", -1, 2 ],
  [ Moves.MIND_READER, "Mind Reader", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "User's next attack is guaranteed to hit.", -1, 2 ],
  [ Moves.NIGHTMARE, "Nightmare", Type.GHOST, MOVE_CATEGORY.STATUS, -1, 100, 15, "", "The sleeping opponent loses 25% of its max HP each turn.", -1, 2 ],
  [ Moves.FLAME_WHEEL, "Flame Wheel", Type.FIRE, MOVE_CATEGORY.PHYSICAL, 60, 100, 25, "", "May burn opponent.", 10, 2 ],
  [ Moves.SNORE, "Snore", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 50, 100, 15, "", "Can only be used if asleep. May cause flinching.", 30, 2 ],
  [ Moves.CURSE, "Curse", Type.GHOST, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Ghosts lose 50% of max HP and curse the opponent; Non-Ghosts raise Attack, Defense and lower Speed.", -1, 2 ],
  [ Moves.FLAIL, "Flail", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, -1, 100, 15, "", "The lower the user's HP, the higher the power.", -1, 2 ],
  [ Moves.CONVERSION_2, "Conversion 2", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 30, "", "User changes type to become resistant to opponent's last move.", -1, 2 ],
  [ Moves.AEROBLAST, "Aeroblast", Type.FLYING, MOVE_CATEGORY.SPECIAL, 100, 95, 5, "", "High critical hit ratio.", -1, 2 ],
  [ Moves.COTTON_SPORE, "Cotton Spore", Type.GRASS, MOVE_CATEGORY.STATUS, -1, 100, 40, "", "Sharply lowers opponent's Speed.", -1, 2 ],
  [ Moves.REVERSAL, "Reversal", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, -1, 100, 15, "TM134", "The lower the user's HP, the higher the power.", -1, 2 ],
  [ Moves.SPITE, "Spite", Type.GHOST, MOVE_CATEGORY.STATUS, -1, 100, 10, "", "The opponent's last move loses 2-5 PP.", -1, 2 ],
  [ Moves.POWDER_SNOW, "Powder Snow", Type.ICE, MOVE_CATEGORY.SPECIAL, 40, 100, 25, "", "May freeze opponent.", 10, 2 ],
  [ Moves.PROTECT, "Protect", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "TM07", "Protects the user, but may fail if used consecutively.", -1, 2 ],
  [ Moves.MACH_PUNCH, "Mach Punch", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 40, 100, 30, "", "User attacks first.", -1, 2 ],
  [ Moves.SCARY_FACE, "Scary Face", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 10, "TM06", "Sharply lowers opponent's Speed.", -1, 2 ],
  [ Moves.FEINT_ATTACK, "Feint Attack", Type.DARK, MOVE_CATEGORY.PHYSICAL, 60, 999, 20, "", "Ignores Accuracy and Evasiveness.", -1, 2 ],
  [ Moves.SWEET_KISS, "Sweet Kiss", Type.FAIRY, MOVE_CATEGORY.STATUS, -1, 75, 10, "", "Confuses opponent.", -1, 2 ],
  [ Moves.BELLY_DRUM, "Belly Drum", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "User loses 50% of its max HP, but Attack raises to maximum.", -1, 2 ],
  [ Moves.SLUDGE_BOMB, "Sludge Bomb", Type.POISON, MOVE_CATEGORY.SPECIAL, 90, 100, 10, "TM148", "May poison opponent.", 30, 2 ],
  [ Moves.MUD_SLAP, "Mud-Slap", Type.GROUND, MOVE_CATEGORY.SPECIAL, 20, 100, 10, "TM05", "Lowers opponent's Accuracy.", 100, 2 ],
  [ Moves.OCTAZOOKA, "Octazooka", Type.WATER, MOVE_CATEGORY.SPECIAL, 65, 85, 10, "", "May lower opponent's Accuracy.", 50, 2 ],
  [ Moves.SPIKES, "Spikes", Type.GROUND, MOVE_CATEGORY.STATUS, -1, -1, 20, "TM90", "Hurts opponents when they switch into battle.", -1, 2 ],
  [ Moves.ZAP_CANNON, "Zap Cannon", Type.ELECTRIC, MOVE_CATEGORY.SPECIAL, 120, 50, 5, "", "Paralyzes opponent.", 100, 2 ],
  [ Moves.FORESIGHT, "Foresight", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 40, "", "Resets opponent's Evasiveness, and allows Normal- and Fighting-type attacks to hit Ghosts.", -1, 2 ],
  [ Moves.DESTINY_BOND, "Destiny Bond", Type.GHOST, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "If the user faints, the opponent also faints.", -1, 2 ],
  [ Moves.PERISH_SONG, "Perish Song", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "Any Pokémon in play when this attack is used faints in 3 turns.", -1, 2 ],
  [ Moves.ICY_WIND, "Icy Wind", Type.ICE, MOVE_CATEGORY.SPECIAL, 55, 95, 15, "TM34", "Lowers opponent's Speed.", 100, 2 ],
  [ Moves.DETECT, "Detect", Type.FIGHTING, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "Protects the user, but may fail if used consecutively.", -1, 2 ],
  [ Moves.BONE_RUSH, "Bone Rush", Type.GROUND, MOVE_CATEGORY.PHYSICAL, 25, 90, 10, "", "Hits 2-5 times in one turn.", -1, 2 ],
  [ Moves.LOCK_ON, "Lock-On", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "User's next attack is guaranteed to hit.", -1, 2 ],
  [ Moves.OUTRAGE, "Outrage", Type.DRAGON, MOVE_CATEGORY.PHYSICAL, 120, 100, 10, "TM156", "User attacks for 2-3 turns but then becomes confused.", -1, 2 ],
  [ Moves.SANDSTORM, "Sandstorm", Type.ROCK, MOVE_CATEGORY.STATUS, -1, -1, 10, "TM51", "Creates a sandstorm for 5 turns.", -1, 2 ],
  [ Moves.GIGA_DRAIN, "Giga Drain", Type.GRASS, MOVE_CATEGORY.SPECIAL, 75, 100, 10, "TM111", "User recovers half the HP inflicted on opponent.", -1, 2 ],
  [ Moves.ENDURE, "Endure", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "TM47", "Always left with at least 1 HP, but may fail if used consecutively.", -1, 2 ],
  [ Moves.CHARM, "Charm", Type.FAIRY, MOVE_CATEGORY.STATUS, -1, 100, 20, "TM02", "Sharply lowers opponent's Attack.", -1, 2 ],
  [ Moves.ROLLOUT, "Rollout", Type.ROCK, MOVE_CATEGORY.PHYSICAL, 30, 90, 20, "", "Doubles in power each turn for 5 turns.", -1, 2 ],
  [ Moves.FALSE_SWIPE, "False Swipe", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 40, 100, 40, "TM57", "Always leaves opponent with at least 1 HP.", -1, 2 ],
  [ Moves.SWAGGER, "Swagger", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 85, 15, "", "Confuses opponent, but sharply raises its Attack.", -1, 2 ],
  [ Moves.MILK_DRINK, "Milk Drink", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "User recovers half its max HP.", -1, 2 ],
  [ Moves.SPARK, "Spark", Type.ELECTRIC, MOVE_CATEGORY.PHYSICAL, 65, 100, 20, "", "May paralyze opponent.", 30, 2 ],
  [ Moves.FURY_CUTTER, "Fury Cutter", Type.BUG, MOVE_CATEGORY.PHYSICAL, 40, 95, 20, "", "Power increases each turn.", -1, 2 ],
  [ Moves.STEEL_WING, "Steel Wing", Type.STEEL, MOVE_CATEGORY.PHYSICAL, 70, 90, 25, "", "May raise user's Defense.", 10, 2 ],
  [ Moves.MEAN_LOOK, "Mean Look", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "Opponent cannot flee or switch.", -1, 2 ],
  [ Moves.ATTRACT, "Attract", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 15, "", "If opponent is the opposite gender, it's less likely to attack.", -1, 2 ],
  [ Moves.SLEEP_TALK, "Sleep Talk", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "TM70", "User performs one of its own moves while sleeping.", -1, 2 ],
  [ Moves.HEAL_BELL, "Heal Bell", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "Heals the user's party's status conditions.", -1, 2 ],
  [ Moves.RETURN, "Return", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, -1, 100, 20, "", "Power increases with higher Friendship.", -1, 2 ],
  [ Moves.PRESENT, "Present", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, -1, 90, 15, "", "Either deals damage or heals.", -1, 2 ],
  [ Moves.FRUSTRATION, "Frustration", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, -1, 100, 20, "", "Power decreases with higher Friendship.", -1, 2 ],
  [ Moves.SAFEGUARD, "Safeguard", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 25, "", "The user's party is protected from status conditions.", -1, 2 ],
  [ Moves.PAIN_SPLIT, "Pain Split", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "The user's and opponent's HP becomes the average of both.", -1, 2 ],
  [ Moves.SACRED_FIRE, "Sacred Fire", Type.FIRE, MOVE_CATEGORY.PHYSICAL, 100, 95, 5, "", "May burn opponent.", 50, 2 ],
  [ Moves.MAGNITUDE, "Magnitude", Type.GROUND, MOVE_CATEGORY.PHYSICAL, -1, 100, 30, "", "Hits with random power.", -1, 2 ],
  [ Moves.DYNAMIC_PUNCH, "Dynamic Punch", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 100, 50, 5, "", "Confuses opponent.", 100, 2 ],
  [ Moves.MEGAHORN, "Megahorn", Type.BUG, MOVE_CATEGORY.PHYSICAL, 120, 85, 10, "", "", -1, 2 ],
  [ Moves.DRAGON_BREATH, "Dragon Breath", Type.DRAGON, MOVE_CATEGORY.SPECIAL, 60, 100, 20, "", "May paralyze opponent.", 30, 2 ],
  [ Moves.BATON_PASS, "Baton Pass", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 40, "TM132", "User switches out and gives stat changes to the incoming Pokémon.", -1, 2 ],
  [ Moves.ENCORE, "Encore", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 5, "TM122", "Forces opponent to keep using its last move for 3 turns.", -1, 2 ],
  [ Moves.PURSUIT, "Pursuit", Type.DARK, MOVE_CATEGORY.PHYSICAL, 40, 100, 20, "", "Double power if the opponent is switching out.", -1, 2 ],
  [ Moves.RAPID_SPIN, "Rapid Spin", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 50, 100, 40, "", "Raises user's Speed and removes entry hazards and trap move effects.", 100, 2 ],
  [ Moves.SWEET_SCENT, "Sweet Scent", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 20, "", "Lowers opponent's Evasiveness.", -1, 2 ],
  [ Moves.IRON_TAIL, "Iron Tail", Type.STEEL, MOVE_CATEGORY.PHYSICAL, 100, 75, 15, "", "May lower opponent's Defense.", 30, 2 ],
  [ Moves.METAL_CLAW, "Metal Claw", Type.STEEL, MOVE_CATEGORY.PHYSICAL, 50, 95, 35, "TM31", "May raise user's Attack.", 10, 2 ],
  [ Moves.VITAL_THROW, "Vital Throw", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 70, 999, 10, "", "User attacks last, but ignores Accuracy and Evasiveness.", -1, 2 ],
  [ Moves.MORNING_SUN, "Morning Sun", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "User recovers HP. Amount varies with the weather.", -1, 2 ],
  [ Moves.SYNTHESIS, "Synthesis", Type.GRASS, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "User recovers HP. Amount varies with the weather.", -1, 2 ],
  [ Moves.MOONLIGHT, "Moonlight", Type.FAIRY, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "User recovers HP. Amount varies with the weather.", -1, 2 ],
  [ Moves.HIDDEN_POWER, "Hidden Power", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 60, 100, 15, "", "Type and power depends on user's IVs.", -1, 2 ],
  [ Moves.CROSS_CHOP, "Cross Chop", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 100, 80, 5, "", "High critical hit ratio.", -1, 2 ],
  [ Moves.TWISTER, "Twister", Type.DRAGON, MOVE_CATEGORY.SPECIAL, 40, 100, 20, "", "May cause flinching. Hits Pokémon using Fly/Bounce with double power.", 20, 2 ],
  [ Moves.RAIN_DANCE, "Rain Dance", Type.WATER, MOVE_CATEGORY.STATUS, -1, -1, 5, "TM50", "Makes it rain for 5 turns.", -1, 2 ],
  [ Moves.SUNNY_DAY, "Sunny Day", Type.FIRE, MOVE_CATEGORY.STATUS, -1, -1, 5, "TM49", "Makes it sunny for 5 turns.", -1, 2 ],
  [ Moves.CRUNCH, "Crunch", Type.DARK, MOVE_CATEGORY.PHYSICAL, 80, 100, 15, "TM108", "May lower opponent's Defense.", 20, 2 ],
  [ Moves.MIRROR_COAT, "Mirror Coat", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, -1, 100, 20, "", "When hit by a Special Attack, user strikes back with 2x power.", -1, 2 ],
  [ Moves.PSYCH_UP, "Psych Up", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Copies the opponent's stat changes.", -1, 2 ],
  [ Moves.EXTREME_SPEED, "Extreme Speed", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 80, 100, 5, "", "User attacks first.", -1, 2 ],
  [ Moves.ANCIENT_POWER, "Ancient Power", Type.ROCK, MOVE_CATEGORY.SPECIAL, 60, 100, 5, "", "May raise all user's stats at once.", 10, 2 ],
  [ Moves.SHADOW_BALL, "Shadow Ball", Type.GHOST, MOVE_CATEGORY.SPECIAL, 80, 100, 15, "TM114", "May lower opponent's Special Defense.", 20, 2 ],
  [ Moves.FUTURE_SIGHT, "Future Sight", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 120, 100, 10, "", "Damage occurs 2 turns later.", -1, 2 ],
  [ Moves.ROCK_SMASH, "Rock Smash", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 40, 100, 15, "", "May lower opponent's Defense.", 50, 2 ],
  [ Moves.WHIRLPOOL, "Whirlpool", Type.WATER, MOVE_CATEGORY.SPECIAL, 35, 85, 15, "", "Traps opponent, damaging them for 4-5 turns.", 100, 2 ],
  [ Moves.BEAT_UP, "Beat Up", Type.DARK, MOVE_CATEGORY.PHYSICAL, -1, 100, 10, "", "Each Pokémon in user's party attacks.", -1, 2 ],
  [ Moves.FAKE_OUT, "Fake Out", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 40, 100, 10, "", "User attacks first, foe flinches. Only usable on first turn.", 100, 3 ],
  [ Moves.UPROAR, "Uproar", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 90, 100, 10, "", "User attacks for 3 turns and prevents sleep.", -1, 3 ],
  [ Moves.STOCKPILE, "Stockpile", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Stores energy for use with Spit Up and Swallow.", -1, 3 ],
  [ Moves.SPIT_UP, "Spit Up", Type.NORMAL, MOVE_CATEGORY.SPECIAL, -1, 100, 10, "", "Power depends on how many times the user performed Stockpile.", -1, 3 ],
  [ Moves.SWALLOW, "Swallow", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "The more times the user has performed Stockpile, the more HP is recovered.", -1, 3 ],
  [ Moves.HEAT_WAVE, "Heat Wave", Type.FIRE, MOVE_CATEGORY.SPECIAL, 95, 90, 10, "TM118", "May burn opponent.", 10, 3 ],
  [ Moves.HAIL, "Hail", Type.ICE, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Non-Ice types are damaged for 5 turns.", -1, 3 ],
  [ Moves.TORMENT, "Torment", Type.DARK, MOVE_CATEGORY.STATUS, -1, 100, 15, "", "Opponent cannot use the same move in a row.", -1, 3 ],
  [ Moves.FLATTER, "Flatter", Type.DARK, MOVE_CATEGORY.STATUS, -1, 100, 15, "", "Confuses opponent, but raises its Special Attack.", -1, 3 ],
  [ Moves.WILL_O_WISP, "Will-O-Wisp", Type.FIRE, MOVE_CATEGORY.STATUS, -1, 85, 15, "TM107", "Burns opponent.", -1, 3 ],
  [ Moves.MEMENTO, "Memento", Type.DARK, MOVE_CATEGORY.STATUS, -1, 100, 10, "", "User faints, sharply lowers opponent's Attack and Special Attack.", -1, 3 ],
  [ Moves.FACADE, "Facade", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 70, 100, 20, "TM25", "Power doubles if user is burned, poisoned, or paralyzed.", -1, 3 ],
  [ Moves.FOCUS_PUNCH, "Focus Punch", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 150, 100, 20, "", "If the user is hit before attacking, it flinches instead.", -1, 3 ],
  [ Moves.SMELLING_SALTS, "Smelling Salts", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 70, 100, 10, "", "Power doubles if opponent is paralyzed, but cures it.", -1, 3 ],
  [ Moves.FOLLOW_ME, "Follow Me", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "In Double Battle, the user takes all the attacks.", -1, 3 ],
  [ Moves.NATURE_POWER, "Nature Power", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Uses a certain move based on the current terrain.", -1, 3 ],
  [ Moves.CHARGE, "Charge", Type.ELECTRIC, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Raises user's Special Defense and next Electric move's power increases.", -1, 3 ],
  [ Moves.TAUNT, "Taunt", Type.DARK, MOVE_CATEGORY.STATUS, -1, 100, 20, "TM87", "Opponent can only use moves that attack.", -1, 3 ],
  [ Moves.HELPING_HAND, "Helping Hand", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "TM130", "In Double Battles, boosts the power of the partner's move.", -1, 3 ],
  [ Moves.TRICK, "Trick", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, 100, 10, "TM109", "Swaps held items with the opponent.", -1, 3 ],
  [ Moves.ROLE_PLAY, "Role Play", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "User copies the opponent's Ability.", -1, 3 ],
  [ Moves.WISH, "Wish", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "The user recovers HP in the following turn.", -1, 3 ],
  [ Moves.ASSIST, "Assist", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "User performs a move known by its allies at random.", -1, 3 ],
  [ Moves.INGRAIN, "Ingrain", Type.GRASS, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "User restores HP each turn. User cannot escape/switch.", -1, 3 ],
  [ Moves.SUPERPOWER, "Superpower", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 120, 100, 5, "", "Lowers user's Attack and Defense.", 100, 3 ],
  [ Moves.MAGIC_COAT, "Magic Coat", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "Reflects moves that cause status conditions back to the attacker.", -1, 3 ],
  [ Moves.RECYCLE, "Recycle", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "User's used hold item is restored.", -1, 3 ],
  [ Moves.REVENGE, "Revenge", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 60, 100, 10, "", "Power increases if user was hit first.", -1, 3 ],
  [ Moves.BRICK_BREAK, "Brick Break", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 75, 100, 15, "TM58", "Breaks through Reflect and Light Screen barriers.", -1, 3 ],
  [ Moves.YAWN, "Yawn", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Puts opponent to sleep in the next turn.", -1, 3 ],
  [ Moves.KNOCK_OFF, "Knock Off", Type.DARK, MOVE_CATEGORY.PHYSICAL, 65, 100, 20, "", "Removes opponent's held item for the rest of the battle.", -1, 3 ],
  [ Moves.ENDEAVOR, "Endeavor", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, -1, 100, 5, "", "Reduces opponent's HP to same as user's.", -1, 3 ],
  [ Moves.ERUPTION, "Eruption", Type.FIRE, MOVE_CATEGORY.SPECIAL, 150, 100, 5, "", "Stronger when the user's HP is higher.", -1, 3 ],
  [ Moves.SKILL_SWAP, "Skill Swap", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "TM98", "The user swaps Abilities with the opponent.", -1, 3 ],
  [ Moves.IMPRISON, "Imprison", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "TM92", "Opponent is unable to use moves that the user also knows.", -1, 3 ],
  [ Moves.REFRESH, "Refresh", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Cures paralysis, poison, and burns.", -1, 3 ],
  [ Moves.GRUDGE, "Grudge", Type.GHOST, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "If the users faints after using this move, the PP for the opponent's last move is depleted.", -1, 3 ],
  [ Moves.SNATCH, "Snatch", Type.DARK, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Steals the effects of the opponent's next move.", -1, 3 ],
  [ Moves.SECRET_POWER, "Secret Power", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 70, 100, 20, "", "Effects of the attack vary with the location.", 30, 3 ],
  [ Moves.DIVE, "Dive", Type.WATER, MOVE_CATEGORY.PHYSICAL, 80, 100, 10, "", "Dives underwater on first turn, attacks on second turn.", -1, 3 ],
  [ Moves.ARM_THRUST, "Arm Thrust", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 15, 100, 20, "", "Hits 2-5 times in one turn.", -1, 3 ],
  [ Moves.CAMOUFLAGE, "Camouflage", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Changes user's type according to the location.", -1, 3 ],
  [ Moves.TAIL_GLOW, "Tail Glow", Type.BUG, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Drastically raises user's Special Attack.", -1, 3 ],
  [ Moves.LUSTER_PURGE, "Luster Purge", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 70, 100, 5, "", "May lower opponent's Special Defense.", 50, 3 ],
  [ Moves.MIST_BALL, "Mist Ball", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 70, 100, 5, "", "May lower opponent's Special Attack.", 50, 3 ],
  [ Moves.FEATHER_DANCE, "Feather Dance", Type.FLYING, MOVE_CATEGORY.STATUS, -1, 100, 15, "", "Sharply lowers opponent's Attack.", -1, 3 ],
  [ Moves.TEETER_DANCE, "Teeter Dance", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 20, "", "Confuses all Pokémon.", -1, 3 ],
  [ Moves.BLAZE_KICK, "Blaze Kick", Type.FIRE, MOVE_CATEGORY.PHYSICAL, 85, 90, 10, "", "High critical hit ratio. May burn opponent.", 10, 3 ],
  [ Moves.MUD_SPORT, "Mud Sport", Type.GROUND, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "Weakens the power of Electric-type moves.", -1, 3 ],
  [ Moves.ICE_BALL, "Ice Ball", Type.ICE, MOVE_CATEGORY.PHYSICAL, 30, 90, 20, "", "Doubles in power each turn for 5 turns.", -1, 3 ],
  [ Moves.NEEDLE_ARM, "Needle Arm", Type.GRASS, MOVE_CATEGORY.PHYSICAL, 60, 100, 15, "", "May cause flinching.", 30, 3 ],
  [ Moves.SLACK_OFF, "Slack Off", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "User recovers half its max HP.", -1, 3 ],
  [ Moves.HYPER_VOICE, "Hyper Voice", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 90, 100, 10, "TM117", "", -1, 3 ],
  [ Moves.POISON_FANG, "Poison Fang", Type.POISON, MOVE_CATEGORY.PHYSICAL, 50, 100, 15, "", "May badly poison opponent.", 50, 3 ],
  [ Moves.CRUSH_CLAW, "Crush Claw", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 75, 95, 10, "", "May lower opponent's Defense.", 50, 3 ],
  [ Moves.BLAST_BURN, "Blast Burn", Type.FIRE, MOVE_CATEGORY.SPECIAL, 150, 90, 5, "TM153", "User must recharge next turn.", -1, 3 ],
  [ Moves.HYDRO_CANNON, "Hydro Cannon", Type.WATER, MOVE_CATEGORY.SPECIAL, 150, 90, 5, "TM154", "User must recharge next turn.", -1, 3 ],
  [ Moves.METEOR_MASH, "Meteor Mash", Type.STEEL, MOVE_CATEGORY.PHYSICAL, 90, 90, 10, "", "May raise user's Attack.", 20, 3 ],
  [ Moves.ASTONISH, "Astonish", Type.GHOST, MOVE_CATEGORY.PHYSICAL, 30, 100, 15, "", "May cause flinching.", 30, 3 ],
  [ Moves.WEATHER_BALL, "Weather Ball", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 50, 100, 10, "", "Move's power and type changes with the weather.", -1, 3 ],
  [ Moves.AROMATHERAPY, "Aromatherapy", Type.GRASS, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "Cures all status problems in your party.", -1, 3 ],
  [ Moves.FAKE_TEARS, "Fake Tears", Type.DARK, MOVE_CATEGORY.STATUS, -1, 100, 20, "TM03", "Sharply lowers opponent's Special Defense.", -1, 3 ],
  [ Moves.AIR_CUTTER, "Air Cutter", Type.FLYING, MOVE_CATEGORY.SPECIAL, 60, 95, 25, "TM40", "High critical hit ratio.", -1, 3 ],
  [ Moves.OVERHEAT, "Overheat", Type.FIRE, MOVE_CATEGORY.SPECIAL, 130, 90, 5, "TM157", "Sharply lowers user's Special Attack.", 100, 3 ],
  [ Moves.ODOR_SLEUTH, "Odor Sleuth", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 40, "", "Resets opponent's Evasiveness, and allows Normal- and Fighting-type attacks to hit Ghosts.", -1, 3 ],
  [ Moves.ROCK_TOMB, "Rock Tomb", Type.ROCK, MOVE_CATEGORY.PHYSICAL, 60, 95, 15, "TM36", "Lowers opponent's Speed.", 100, 3 ],
  [ Moves.SILVER_WIND, "Silver Wind", Type.BUG, MOVE_CATEGORY.SPECIAL, 60, 100, 5, "", "May raise all stats of user at once.", 10, 3 ],
  [ Moves.METAL_SOUND, "Metal Sound", Type.STEEL, MOVE_CATEGORY.STATUS, -1, 85, 40, "", "Sharply lowers opponent's Special Defense.", -1, 3 ],
  [ Moves.GRASS_WHISTLE, "Grass Whistle", Type.GRASS, MOVE_CATEGORY.STATUS, -1, 55, 15, "", "Puts opponent to sleep.", -1, 3 ],
  [ Moves.TICKLE, "Tickle", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 20, "", "Lowers opponent's Attack and Defense.", -1, 3 ],
  [ Moves.COSMIC_POWER, "Cosmic Power", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Raises user's Defense and Special Defense.", -1, 3 ],
  [ Moves.WATER_SPOUT, "Water Spout", Type.WATER, MOVE_CATEGORY.SPECIAL, 150, 100, 5, "", "The higher the user's HP, the higher the damage caused.", -1, 3 ],
  [ Moves.SIGNAL_BEAM, "Signal Beam", Type.BUG, MOVE_CATEGORY.SPECIAL, 75, 100, 15, "", "May confuse opponent.", 10, 3 ],
  [ Moves.SHADOW_PUNCH, "Shadow Punch", Type.GHOST, MOVE_CATEGORY.PHYSICAL, 60, 999, 20, "", "Ignores Accuracy and Evasiveness.", -1, 3 ],
  [ Moves.EXTRASENSORY, "Extrasensory", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 80, 100, 20, "", "May cause flinching.", 10, 3 ],
  [ Moves.SKY_UPPERCUT, "Sky Uppercut", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 85, 90, 15, "", "Hits the opponent, even during Fly.", -1, 3 ],
  [ Moves.SAND_TOMB, "Sand Tomb", Type.GROUND, MOVE_CATEGORY.PHYSICAL, 35, 85, 15, "", "Traps opponent, damaging them for 4-5 turns.", 100, 3 ],
  [ Moves.SHEER_COLD, "Sheer Cold", Type.ICE, MOVE_CATEGORY.SPECIAL, -1, 30, 5, "", "One-Hit-KO, if it hits.", -1, 3 ],
  [ Moves.MUDDY_WATER, "Muddy Water", Type.WATER, MOVE_CATEGORY.SPECIAL, 90, 85, 10, "", "May lower opponent's Accuracy.", 30, 3 ],
  [ Moves.BULLET_SEED, "Bullet Seed", Type.GRASS, MOVE_CATEGORY.PHYSICAL, 25, 100, 30, "TM56", "Hits 2-5 times in one turn.", -1, 3 ],
  [ Moves.AERIAL_ACE, "Aerial Ace", Type.FLYING, MOVE_CATEGORY.PHYSICAL, 60, 999, 20, "TM27", "Ignores Accuracy and Evasiveness.", -1, 3 ],
  [ Moves.ICICLE_SPEAR, "Icicle Spear", Type.ICE, MOVE_CATEGORY.PHYSICAL, 25, 100, 30, "", "Hits 2-5 times in one turn.", -1, 3 ],
  [ Moves.IRON_DEFENSE, "Iron Defense", Type.STEEL, MOVE_CATEGORY.STATUS, -1, -1, 15, "TM104", "Sharply raises user's Defense.", -1, 3 ],
  [ Moves.BLOCK, "Block", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "Opponent cannot flee or switch.", -1, 3 ],
  [ Moves.HOWL, "Howl", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 40, "", "Raises Attack of allies.", -1, 3 ],
  [ Moves.DRAGON_CLAW, "Dragon Claw", Type.DRAGON, MOVE_CATEGORY.PHYSICAL, 80, 100, 15, "TM78", "", -1, 3 ],
  [ Moves.FRENZY_PLANT, "Frenzy Plant", Type.GRASS, MOVE_CATEGORY.SPECIAL, 150, 90, 5, "TM155", "User must recharge next turn.", -1, 3 ],
  [ Moves.BULK_UP, "Bulk Up", Type.FIGHTING, MOVE_CATEGORY.STATUS, -1, -1, 20, "TM64", "Raises user's Attack and Defense.", -1, 3 ],
  [ Moves.BOUNCE, "Bounce", Type.FLYING, MOVE_CATEGORY.PHYSICAL, 85, 85, 5, "", "Springs up on first turn, attacks on second. May paralyze opponent.", 30, 3 ],
  [ Moves.MUD_SHOT, "Mud Shot", Type.GROUND, MOVE_CATEGORY.SPECIAL, 55, 95, 15, "TM35", "Lowers opponent's Speed.", 100, 3 ],
  [ Moves.POISON_TAIL, "Poison Tail", Type.POISON, MOVE_CATEGORY.PHYSICAL, 50, 100, 25, "TM26", "High critical hit ratio. May poison opponent.", 10, 3 ],
  [ Moves.COVET, "Covet", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 60, 100, 25, "", "Opponent's item is stolen by the user.", -1, 3 ],
  [ Moves.VOLT_TACKLE, "Volt Tackle", Type.ELECTRIC, MOVE_CATEGORY.PHYSICAL, 120, 100, 15, "", "User receives recoil damage. May paralyze opponent.", 10, 3 ],
  [ Moves.MAGICAL_LEAF, "Magical Leaf", Type.GRASS, MOVE_CATEGORY.SPECIAL, 60, 999, 20, "TM33", "Ignores Accuracy and Evasiveness.", -1, 3 ],
  [ Moves.WATER_SPORT, "Water Sport", Type.WATER, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "Weakens the power of Fire-type moves.", -1, 3 ],
  [ Moves.CALM_MIND, "Calm Mind", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 20, "TM129", "Raises user's Special Attack and Special Defense.", -1, 3 ],
  [ Moves.LEAF_BLADE, "Leaf Blade", Type.GRASS, MOVE_CATEGORY.PHYSICAL, 90, 100, 15, "", "High critical hit ratio.", -1, 3 ],
  [ Moves.DRAGON_DANCE, "Dragon Dance", Type.DRAGON, MOVE_CATEGORY.STATUS, -1, -1, 20, "TM100", "Raises user's Attack and Speed.", -1, 3 ],
  [ Moves.ROCK_BLAST, "Rock Blast", Type.ROCK, MOVE_CATEGORY.PHYSICAL, 25, 90, 10, "TM76", "Hits 2-5 times in one turn.", -1, 3 ],
  [ Moves.SHOCK_WAVE, "Shock Wave", Type.ELECTRIC, MOVE_CATEGORY.SPECIAL, 60, 999, 20, "", "Ignores Accuracy and Evasiveness.", -1, 3 ],
  [ Moves.WATER_PULSE, "Water Pulse", Type.WATER, MOVE_CATEGORY.SPECIAL, 60, 100, 20, "TM11", "May confuse opponent.", 20, 3 ],
  [ Moves.DOOM_DESIRE, "Doom Desire", Type.STEEL, MOVE_CATEGORY.SPECIAL, 140, 100, 5, "", "Damage occurs 2 turns later.", -1, 3 ],
  [ Moves.PSYCHO_BOOST, "Psycho Boost", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 140, 90, 5, "", "Sharply lowers user's Special Attack.", 100, 3 ],
  [ Moves.ROOST, "Roost", Type.FLYING, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "User recovers half of its max HP and loses the Flying type temporarily.", -1, 4 ],
  [ Moves.GRAVITY, "Gravity", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 5, "", "Prevents moves like Fly and Bounce and the Ability Levitate for 5 turns.", -1, 4 ],
  [ Moves.MIRACLE_EYE, "Miracle Eye", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 40, "", "Resets opponent's Evasiveness, removes Dark's Psychic immunity.", -1, 4 ],
  [ Moves.WAKE_UP_SLAP, "Wake-Up Slap", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 70, 100, 10, "", "Power doubles if opponent is asleep, but wakes it up.", -1, 4 ],
  [ Moves.HAMMER_ARM, "Hammer Arm", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 100, 90, 10, "", "Lowers user's Speed.", 100, 4 ],
  [ Moves.GYRO_BALL, "Gyro Ball", Type.STEEL, MOVE_CATEGORY.PHYSICAL, -1, 100, 5, "", "The slower the user, the stronger the attack.", -1, 4 ],
  [ Moves.HEALING_WISH, "Healing Wish", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "The user faints and the next Pokémon released is fully healed.", -1, 4 ],
  [ Moves.BRINE, "Brine", Type.WATER, MOVE_CATEGORY.SPECIAL, 65, 100, 10, "", "Power doubles if opponent's HP is less than 50%.", -1, 4 ],
  [ Moves.NATURAL_GIFT, "Natural Gift", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, -1, 100, 15, "", "Power and type depend on the user's held berry.", -1, 4 ],
  [ Moves.FEINT, "Feint", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 30, 100, 10, "", "Only hits if opponent uses Protect or Detect in the same turn.", -1, 4 ],
  [ Moves.PLUCK, "Pluck", Type.FLYING, MOVE_CATEGORY.PHYSICAL, 60, 100, 20, "", "If the opponent is holding a berry, its effect is stolen by user.", -1, 4 ],
  [ Moves.TAILWIND, "Tailwind", Type.FLYING, MOVE_CATEGORY.STATUS, -1, -1, 15, "TM113", "Doubles Speed for 4 turns.", -1, 4 ],
  [ Moves.ACUPRESSURE, "Acupressure", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 30, "", "Sharply raises a random stat.", -1, 4 ],
  [ Moves.METAL_BURST, "Metal Burst", Type.STEEL, MOVE_CATEGORY.PHYSICAL, -1, 100, 10, "", "Deals damage equal to 1.5x opponent's attack.", -1, 4 ],
  [ Moves.U_TURN, "U-turn", Type.BUG, MOVE_CATEGORY.PHYSICAL, 70, 100, 20, "TM60", "User switches out immediately after attacking.", -1, 4 ],
  [ Moves.CLOSE_COMBAT, "Close Combat", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 120, 100, 5, "TM167", "Lowers user's Defense and Special Defense.", 100, 4 ],
  [ Moves.PAYBACK, "Payback", Type.DARK, MOVE_CATEGORY.PHYSICAL, 50, 100, 10, "", "Power doubles if the user was attacked first.", -1, 4 ],
  [ Moves.ASSURANCE, "Assurance", Type.DARK, MOVE_CATEGORY.PHYSICAL, 60, 100, 10, "", "Power doubles if opponent already took damage in the same turn.", -1, 4 ],
  [ Moves.EMBARGO, "Embargo", Type.DARK, MOVE_CATEGORY.STATUS, -1, 100, 15, "", "Opponent cannot use items.", -1, 4 ],
  [ Moves.FLING, "Fling", Type.DARK, MOVE_CATEGORY.PHYSICAL, -1, 100, 10, "TM43", "Power depends on held item.", -1, 4 ],
  [ Moves.PSYCHO_SHIFT, "Psycho Shift", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, 100, 10, "", "Transfers user's status condition to the opponent.", -1, 4 ],
  [ Moves.TRUMP_CARD, "Trump Card", Type.NORMAL, MOVE_CATEGORY.SPECIAL, -1, 999, 5, "", "The lower the PP, the higher the power.", -1, 4 ],
  [ Moves.HEAL_BLOCK, "Heal Block", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, 100, 15, "", "Prevents the opponent from restoring HP for 5 turns.", -1, 4 ],
  [ Moves.WRING_OUT, "Wring Out", Type.NORMAL, MOVE_CATEGORY.SPECIAL, -1, 100, 5, "", "The higher the opponent's HP, the higher the damage.", -1, 4 ],
  [ Moves.POWER_TRICK, "Power Trick", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "User's own Attack and Defense switch.", -1, 4 ],
  [ Moves.GASTRO_ACID, "Gastro Acid", Type.POISON, MOVE_CATEGORY.STATUS, -1, 100, 10, "", "Cancels out the effect of the opponent's Ability.", -1, 4 ],
  [ Moves.LUCKY_CHANT, "Lucky Chant", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 30, "", "Opponent cannot land critical hits for 5 turns.", -1, 4 ],
  [ Moves.ME_FIRST, "Me First", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "User copies the opponent's attack with 1.5× power.", -1, 4 ],
  [ Moves.COPYCAT, "Copycat", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Copies opponent's last move.", -1, 4 ],
  [ Moves.POWER_SWAP, "Power Swap", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "User and opponent swap Attack and Special Attack.", -1, 4 ],
  [ Moves.GUARD_SWAP, "Guard Swap", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "User and opponent swap Defense and Special Defense.", -1, 4 ],
  [ Moves.PUNISHMENT, "Punishment", Type.DARK, MOVE_CATEGORY.PHYSICAL, -1, 100, 5, "", "Power increases when opponent's stats have been raised.", -1, 4 ],
  [ Moves.LAST_RESORT, "Last Resort", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 140, 100, 5, "", "Can only be used after all other moves are used.", -1, 4 ],
  [ Moves.WORRY_SEED, "Worry Seed", Type.GRASS, MOVE_CATEGORY.STATUS, -1, 100, 10, "", "Changes the opponent's Ability to Insomnia.", -1, 4 ],
  [ Moves.SUCKER_PUNCH, "Sucker Punch", Type.DARK, MOVE_CATEGORY.PHYSICAL, 70, 100, 5, "", "User attacks first, but only works if opponent is readying an attack.", -1, 4 ],
  [ Moves.TOXIC_SPIKES, "Toxic Spikes", Type.POISON, MOVE_CATEGORY.STATUS, -1, -1, 20, "TM91", "Poisons opponents when they switch into battle.", -1, 4 ],
  [ Moves.HEART_SWAP, "Heart Swap", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Stat changes are swapped with the opponent.", -1, 4 ],
  [ Moves.AQUA_RING, "Aqua Ring", Type.WATER, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Restores a little HP each turn.", -1, 4 ],
  [ Moves.MAGNET_RISE, "Magnet Rise", Type.ELECTRIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "User becomes immune to Ground-type moves for 5 turns.", -1, 4 ],
  [ Moves.FLARE_BLITZ, "Flare Blitz", Type.FIRE, MOVE_CATEGORY.PHYSICAL, 120, 100, 15, "TM165", "User receives recoil damage. May burn opponent.", 10, 4 ],
  [ Moves.FORCE_PALM, "Force Palm", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 60, 100, 10, "", "May paralyze opponent.", 30, 4 ],
  [ Moves.AURA_SPHERE, "Aura Sphere", Type.FIGHTING, MOVE_CATEGORY.SPECIAL, 80, 999, 20, "TM112", "Ignores Accuracy and Evasiveness.", -1, 4 ],
  [ Moves.ROCK_POLISH, "Rock Polish", Type.ROCK, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Sharply raises user's Speed.", -1, 4 ],
  [ Moves.POISON_JAB, "Poison Jab", Type.POISON, MOVE_CATEGORY.PHYSICAL, 80, 100, 20, "TM83", "May poison the opponent.", 30, 4 ],
  [ Moves.DARK_PULSE, "Dark Pulse", Type.DARK, MOVE_CATEGORY.SPECIAL, 80, 100, 15, "TM94", "May cause flinching.", 20, 4 ],
  [ Moves.NIGHT_SLASH, "Night Slash", Type.DARK, MOVE_CATEGORY.PHYSICAL, 70, 100, 15, "", "High critical hit ratio.", -1, 4 ],
  [ Moves.AQUA_TAIL, "Aqua Tail", Type.WATER, MOVE_CATEGORY.PHYSICAL, 90, 90, 10, "", "", -1, 4 ],
  [ Moves.SEED_BOMB, "Seed Bomb", Type.GRASS, MOVE_CATEGORY.PHYSICAL, 80, 100, 15, "TM71", "", -1, 4 ],
  [ Moves.AIR_SLASH, "Air Slash", Type.FLYING, MOVE_CATEGORY.SPECIAL, 75, 95, 15, "TM65", "May cause flinching.", 30, 4 ],
  [ Moves.X_SCISSOR, "X-Scissor", Type.BUG, MOVE_CATEGORY.PHYSICAL, 80, 100, 15, "TM105", "", -1, 4 ],
  [ Moves.BUG_BUZZ, "Bug Buzz", Type.BUG, MOVE_CATEGORY.SPECIAL, 90, 100, 10, "TM162", "May lower opponent's Special Defense.", 10, 4 ],
  [ Moves.DRAGON_PULSE, "Dragon Pulse", Type.DRAGON, MOVE_CATEGORY.SPECIAL, 85, 100, 10, "TM115", "", -1, 4 ],
  [ Moves.DRAGON_RUSH, "Dragon Rush", Type.DRAGON, MOVE_CATEGORY.PHYSICAL, 100, 75, 10, "", "May cause flinching.", 20, 4 ],
  [ Moves.POWER_GEM, "Power Gem", Type.ROCK, MOVE_CATEGORY.SPECIAL, 80, 100, 20, "TM101", "", -1, 4 ],
  [ Moves.DRAIN_PUNCH, "Drain Punch", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 75, 100, 10, "TM73", "User recovers half the HP inflicted on opponent.", -1, 4 ],
  [ Moves.VACUUM_WAVE, "Vacuum Wave", Type.FIGHTING, MOVE_CATEGORY.SPECIAL, 40, 100, 30, "", "User attacks first.", -1, 4 ],
  [ Moves.FOCUS_BLAST, "Focus Blast", Type.FIGHTING, MOVE_CATEGORY.SPECIAL, 120, 70, 5, "TM158", "May lower opponent's Special Defense.", 10, 4 ],
  [ Moves.ENERGY_BALL, "Energy Ball", Type.GRASS, MOVE_CATEGORY.SPECIAL, 90, 100, 10, "TM119", "May lower opponent's Special Defense.", 10, 4 ],
  [ Moves.BRAVE_BIRD, "Brave Bird", Type.FLYING, MOVE_CATEGORY.PHYSICAL, 120, 100, 15, "TM164", "User receives recoil damage.", -1, 4 ],
  [ Moves.EARTH_POWER, "Earth Power", Type.GROUND, MOVE_CATEGORY.SPECIAL, 90, 100, 10, "TM133", "May lower opponent's Special Defense.", 10, 4 ],
  [ Moves.SWITCHEROO, "Switcheroo", Type.DARK, MOVE_CATEGORY.STATUS, -1, 100, 10, "", "Swaps held items with the opponent.", -1, 4 ],
  [ Moves.GIGA_IMPACT, "Giga Impact", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 150, 90, 5, "TM152", "User must recharge next turn.", -1, 4 ],
  [ Moves.NASTY_PLOT, "Nasty Plot", Type.DARK, MOVE_CATEGORY.STATUS, -1, -1, 20, "TM140", "Sharply raises user's Special Attack.", -1, 4 ],
  [ Moves.BULLET_PUNCH, "Bullet Punch", Type.STEEL, MOVE_CATEGORY.PHYSICAL, 40, 100, 30, "", "User attacks first.", -1, 4 ],
  [ Moves.AVALANCHE, "Avalanche", Type.ICE, MOVE_CATEGORY.PHYSICAL, 60, 100, 10, "TM46", "Power doubles if user took damage first.", -1, 4 ],
  [ Moves.ICE_SHARD, "Ice Shard", Type.ICE, MOVE_CATEGORY.PHYSICAL, 40, 100, 30, "", "User attacks first.", -1, 4 ],
  [ Moves.SHADOW_CLAW, "Shadow Claw", Type.GHOST, MOVE_CATEGORY.PHYSICAL, 70, 100, 15, "TM61", "High critical hit ratio.", -1, 4 ],
  [ Moves.THUNDER_FANG, "Thunder Fang", Type.ELECTRIC, MOVE_CATEGORY.PHYSICAL, 65, 95, 15, "TM09", "May cause flinching and/or paralyze opponent.", 10, 4 ],
  [ Moves.ICE_FANG, "Ice Fang", Type.ICE, MOVE_CATEGORY.PHYSICAL, 65, 95, 15, "TM10", "May cause flinching and/or freeze opponent.", 10, 4 ],
  [ Moves.FIRE_FANG, "Fire Fang", Type.FIRE, MOVE_CATEGORY.PHYSICAL, 65, 95, 15, "TM08", "May cause flinching and/or burn opponent.", 10, 4 ],
  [ Moves.SHADOW_SNEAK, "Shadow Sneak", Type.GHOST, MOVE_CATEGORY.PHYSICAL, 40, 100, 30, "", "User attacks first.", -1, 4 ],
  [ Moves.MUD_BOMB, "Mud Bomb", Type.GROUND, MOVE_CATEGORY.SPECIAL, 65, 85, 10, "", "May lower opponent's Accuracy.", 30, 4 ],
  [ Moves.PSYCHO_CUT, "Psycho Cut", Type.PSYCHIC, MOVE_CATEGORY.PHYSICAL, 70, 100, 20, "", "High critical hit ratio.", -1, 4 ],
  [ Moves.ZEN_HEADBUTT, "Zen Headbutt", Type.PSYCHIC, MOVE_CATEGORY.PHYSICAL, 80, 90, 15, "TM59", "May cause flinching.", 20, 4 ],
  [ Moves.MIRROR_SHOT, "Mirror Shot", Type.STEEL, MOVE_CATEGORY.SPECIAL, 65, 85, 10, "", "May lower opponent's Accuracy.", 30, 4 ],
  [ Moves.FLASH_CANNON, "Flash Cannon", Type.STEEL, MOVE_CATEGORY.SPECIAL, 80, 100, 10, "TM93", "May lower opponent's Special Defense.", 10, 4 ],
  [ Moves.ROCK_CLIMB, "Rock Climb", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 90, 85, 20, "", "May confuse opponent.", 20, 4 ],
  [ Moves.DEFOG, "Defog", Type.FLYING, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "Lowers opponent's Evasiveness and clears fog.", -1, 4 ],
  [ Moves.TRICK_ROOM, "Trick Room", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 5, "TM161", "Slower Pokémon move first in the turn for 5 turns.", -1, 4 ],
  [ Moves.DRACO_METEOR, "Draco Meteor", Type.DRAGON, MOVE_CATEGORY.SPECIAL, 130, 90, 5, "TM169", "Sharply lowers user's Special Attack.", 100, 4 ],
  [ Moves.DISCHARGE, "Discharge", Type.ELECTRIC, MOVE_CATEGORY.SPECIAL, 80, 100, 15, "", "May paralyze opponent.", 30, 4 ],
  [ Moves.LAVA_PLUME, "Lava Plume", Type.FIRE, MOVE_CATEGORY.SPECIAL, 80, 100, 15, "", "May burn opponent.", 30, 4 ],
  [ Moves.LEAF_STORM, "Leaf Storm", Type.GRASS, MOVE_CATEGORY.SPECIAL, 130, 90, 5, "TM159", "Sharply lowers user's Special Attack.", 100, 4 ],
  [ Moves.POWER_WHIP, "Power Whip", Type.GRASS, MOVE_CATEGORY.PHYSICAL, 120, 85, 10, "", "", -1, 4 ],
  [ Moves.ROCK_WRECKER, "Rock Wrecker", Type.ROCK, MOVE_CATEGORY.PHYSICAL, 150, 90, 5, "", "User must recharge next turn.", -1, 4 ],
  [ Moves.CROSS_POISON, "Cross Poison", Type.POISON, MOVE_CATEGORY.PHYSICAL, 70, 100, 20, "", "High critical hit ratio. May poison opponent.", 10, 4 ],
  [ Moves.GUNK_SHOT, "Gunk Shot", Type.POISON, MOVE_CATEGORY.PHYSICAL, 120, 80, 5, "TM102", "May poison opponent.", 30, 4 ],
  [ Moves.IRON_HEAD, "Iron Head", Type.STEEL, MOVE_CATEGORY.PHYSICAL, 80, 100, 15, "TM99", "May cause flinching.", 30, 4 ],
  [ Moves.MAGNET_BOMB, "Magnet Bomb", Type.STEEL, MOVE_CATEGORY.PHYSICAL, 60, 999, 20, "", "Ignores Accuracy and Evasiveness.", -1, 4 ],
  [ Moves.STONE_EDGE, "Stone Edge", Type.ROCK, MOVE_CATEGORY.PHYSICAL, 100, 80, 5, "TM150", "High critical hit ratio.", -1, 4 ],
  [ Moves.CAPTIVATE, "Captivate", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 20, "", "Sharply lowers opponent's Special Attack if opposite gender.", -1, 4 ],
  [ Moves.STEALTH_ROCK, "Stealth Rock", Type.ROCK, MOVE_CATEGORY.STATUS, -1, -1, 20, "TM116", "Damages opponent switching into battle.", -1, 4 ],
  [ Moves.GRASS_KNOT, "Grass Knot", Type.GRASS, MOVE_CATEGORY.SPECIAL, -1, 100, 20, "TM81", "The heavier the opponent, the stronger the attack.", -1, 4 ],
  [ Moves.CHATTER, "Chatter", Type.FLYING, MOVE_CATEGORY.SPECIAL, 65, 100, 20, "", "Confuses opponent.", 100, 4 ],
  [ Moves.JUDGMENT, "Judgment", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 100, 100, 10, "", "Type depends on the Arceus Plate being held.", -1, 4 ],
  [ Moves.BUG_BITE, "Bug Bite", Type.BUG, MOVE_CATEGORY.PHYSICAL, 60, 100, 20, "", "Receives the effect from the opponent's held berry.", -1, 4 ],
  [ Moves.CHARGE_BEAM, "Charge Beam", Type.ELECTRIC, MOVE_CATEGORY.SPECIAL, 50, 90, 10, "TM23", "May raise user's Special Attack.", 70, 4 ],
  [ Moves.WOOD_HAMMER, "Wood Hammer", Type.GRASS, MOVE_CATEGORY.PHYSICAL, 120, 100, 15, "", "User receives recoil damage.", -1, 4 ],
  [ Moves.AQUA_JET, "Aqua Jet", Type.WATER, MOVE_CATEGORY.PHYSICAL, 40, 100, 20, "", "User attacks first.", -1, 4 ],
  [ Moves.ATTACK_ORDER, "Attack Order", Type.BUG, MOVE_CATEGORY.PHYSICAL, 90, 100, 15, "", "High critical hit ratio.", -1, 4 ],
  [ Moves.DEFEND_ORDER, "Defend Order", Type.BUG, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Raises user's Defense and Special Defense.", -1, 4 ],
  [ Moves.HEAL_ORDER, "Heal Order", Type.BUG, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "User recovers half its max HP.", -1, 4 ],
  [ Moves.HEAD_SMASH, "Head Smash", Type.ROCK, MOVE_CATEGORY.PHYSICAL, 150, 80, 5, "", "User receives recoil damage.", -1, 4 ],
  [ Moves.DOUBLE_HIT, "Double Hit", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 35, 90, 10, "", "Hits twice in one turn.", -1, 4 ],
  [ Moves.ROAR_OF_TIME, "Roar of Time", Type.DRAGON, MOVE_CATEGORY.SPECIAL, 150, 90, 5, "", "User must recharge next turn.", -1, 4 ],
  [ Moves.SPACIAL_REND, "Spacial Rend", Type.DRAGON, MOVE_CATEGORY.SPECIAL, 100, 95, 5, "", "High critical hit ratio.", -1, 4 ],
  [ Moves.LUNAR_DANCE, "Lunar Dance", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "The user faints but the next Pokémon released is fully healed.", -1, 4 ],
  [ Moves.CRUSH_GRIP, "Crush Grip", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, -1, 100, 5, "", "More powerful when opponent has higher HP.", -1, 4 ],
  [ Moves.MAGMA_STORM, "Magma Storm", Type.FIRE, MOVE_CATEGORY.SPECIAL, 100, 75, 5, "", "Traps opponent, damaging them for 4-5 turns.", 100, 4 ],
  [ Moves.DARK_VOID, "Dark Void", Type.DARK, MOVE_CATEGORY.STATUS, -1, 50, 10, "", "Puts all adjacent opponents to sleep.", -1, 4 ],
  [ Moves.SEED_FLARE, "Seed Flare", Type.GRASS, MOVE_CATEGORY.SPECIAL, 120, 85, 5, "", "May lower opponent's Special Defense.", 40, 4 ],
  [ Moves.OMINOUS_WIND, "Ominous Wind", Type.GHOST, MOVE_CATEGORY.SPECIAL, 60, 100, 5, "", "May raise all user's stats at once.", 10, 4 ],
  [ Moves.SHADOW_FORCE, "Shadow Force", Type.GHOST, MOVE_CATEGORY.PHYSICAL, 120, 100, 5, "", "Disappears on first turn, attacks on second. Can strike through Protect/Detect.", -1, 4 ],
  [ Moves.HONE_CLAWS, "Hone Claws", Type.DARK, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "Raises user's Attack and Accuracy.", -1, 5 ],
  [ Moves.WIDE_GUARD, "Wide Guard", Type.ROCK, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Protects the user's team from multi-target attacks.", -1, 5 ],
  [ Moves.GUARD_SPLIT, "Guard Split", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Averages Defense and Special Defense with the target.", -1, 5 ],
  [ Moves.POWER_SPLIT, "Power Split", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Averages Attack and Special Attack with the target.", -1, 5 ],
  [ Moves.WONDER_ROOM, "Wonder Room", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Swaps every Pokémon's Defense and Special Defense for 5 turns.", -1, 5 ],
  [ Moves.PSYSHOCK, "Psyshock", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 80, 100, 10, "TM54", "Inflicts damage based on the target's Defense, not Special Defense.", -1, 5 ],
  [ Moves.VENOSHOCK, "Venoshock", Type.POISON, MOVE_CATEGORY.SPECIAL, 65, 100, 10, "TM45", "Inflicts double damage if the target is poisoned.", -1, 5 ],
  [ Moves.AUTOTOMIZE, "Autotomize", Type.STEEL, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "Reduces weight and sharply raises Speed.", -1, 5 ],
  [ Moves.RAGE_POWDER, "Rage Powder", Type.BUG, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Forces attacks to hit user, not team-mates.", -1, 5 ],
  [ Moves.TELEKINESIS, "Telekinesis", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "Ignores opponent's Evasiveness for three turns, add Ground immunity.", -1, 5 ],
  [ Moves.MAGIC_ROOM, "Magic Room", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Suppresses the effects of held items for five turns.", -1, 5 ],
  [ Moves.SMACK_DOWN, "Smack Down", Type.ROCK, MOVE_CATEGORY.PHYSICAL, 50, 100, 15, "", "Makes Flying-type Pokémon vulnerable to Ground moves.", 100, 5 ],
  [ Moves.STORM_THROW, "Storm Throw", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 60, 100, 10, "", "Always results in a critical hit.", 100, 5 ],
  [ Moves.FLAME_BURST, "Flame Burst", Type.FIRE, MOVE_CATEGORY.SPECIAL, 70, 100, 15, "", "May also injure nearby Pokémon.", -1, 5 ],
  [ Moves.SLUDGE_WAVE, "Sludge Wave", Type.POISON, MOVE_CATEGORY.SPECIAL, 95, 100, 10, "", "May poison opponent.", 10, 5 ],
  [ Moves.QUIVER_DANCE, "Quiver Dance", Type.BUG, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Raises user's Special Attack, Special Defense and Speed.", -1, 5 ],
  [ Moves.HEAVY_SLAM, "Heavy Slam", Type.STEEL, MOVE_CATEGORY.PHYSICAL, -1, 100, 10, "TM121", "The heavier the user, the stronger the attack.", -1, 5 ],
  [ Moves.SYNCHRONOISE, "Synchronoise", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 120, 100, 10, "", "Hits any Pokémon that shares a type with the user.", -1, 5 ],
  [ Moves.ELECTRO_BALL, "Electro Ball", Type.ELECTRIC, MOVE_CATEGORY.SPECIAL, -1, 100, 10, "TM72", "The faster the user, the stronger the attack.", -1, 5 ],
  [ Moves.SOAK, "Soak", Type.WATER, MOVE_CATEGORY.STATUS, -1, 100, 20, "", "Changes the target's type to water.", -1, 5 ],
  [ Moves.FLAME_CHARGE, "Flame Charge", Type.FIRE, MOVE_CATEGORY.PHYSICAL, 50, 100, 20, "TM38", "Raises user's Speed.", 100, 5 ],
  [ Moves.COIL, "Coil", Type.POISON, MOVE_CATEGORY.STATUS, -1, -1, 20, "", "Raises user's Attack, Defense and Accuracy.", -1, 5 ],
  [ Moves.LOW_SWEEP, "Low Sweep", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 65, 100, 20, "TM39", "Lowers opponent's Speed.", 100, 5 ],
  [ Moves.ACID_SPRAY, "Acid Spray", Type.POISON, MOVE_CATEGORY.SPECIAL, 40, 100, 20, "TM13", "Sharply lowers opponent's Special Defense.", 100, 5 ],
  [ Moves.FOUL_PLAY, "Foul Play", Type.DARK, MOVE_CATEGORY.PHYSICAL, 95, 100, 15, "TM62", "Uses the opponent's Attack stat.", -1, 5 ],
  [ Moves.SIMPLE_BEAM, "Simple Beam", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 15, "", "Changes target's ability to Simple.", -1, 5 ],
  [ Moves.ENTRAINMENT, "Entrainment", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, 100, 15, "", "Makes target's ability same as user's.", -1, 5 ],
  [ Moves.AFTER_YOU, "After You", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "Gives target priority in the next turn.", -1, 5 ],
  [ Moves.ROUND, "Round", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 60, 100, 15, "", "Power increases if teammates use it in the same turn.", -1, 5 ],
  [ Moves.ECHOED_VOICE, "Echoed Voice", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 40, 100, 15, "", "Power increases each turn.", -1, 5 ],
  [ Moves.CHIP_AWAY, "Chip Away", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 70, 100, 20, "", "Ignores opponent's stat changes.", -1, 5 ],
  [ Moves.CLEAR_SMOG, "Clear Smog", Type.POISON, MOVE_CATEGORY.SPECIAL, 50, -1, 15, "", "Removes all of the target's stat changes.", -1, 5 ],
  [ Moves.STORED_POWER, "Stored Power", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 20, 100, 10, "TM41", "Power increases when user's stats have been raised.", -1, 5 ],
  [ Moves.QUICK_GUARD, "Quick Guard", Type.FIGHTING, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "Protects the user's team from high-priority moves.", -1, 5 ],
  [ Moves.ALLY_SWITCH, "Ally Switch", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "User switches with opposite teammate.", -1, 5 ],
  [ Moves.SCALD, "Scald", Type.WATER, MOVE_CATEGORY.SPECIAL, 80, 100, 15, "", "May burn opponent.", 30, 5 ],
  [ Moves.SHELL_SMASH, "Shell Smash", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "Sharply raises user's Attack, Special Attack and Speed but lowers Defense and Special Defense.", -1, 5 ],
  [ Moves.HEAL_PULSE, "Heal Pulse", Type.PSYCHIC, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Restores half the target's max HP.", -1, 5 ],
  [ Moves.HEX, "Hex", Type.GHOST, MOVE_CATEGORY.SPECIAL, 65, 100, 10, "TM29", "Inflicts more damage if the target has a status condition.", -1, 5 ],
  [ Moves.SKY_DROP, "Sky Drop", Type.FLYING, MOVE_CATEGORY.PHYSICAL, 60, 100, 10, "", "Takes opponent into the air on first turn, drops them on second turn.", -1, 5 ],
  [ Moves.SHIFT_GEAR, "Shift Gear", Type.STEEL, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Raises user's Attack and sharply raises Speed.", -1, 5 ],
  [ Moves.CIRCLE_THROW, "Circle Throw", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 60, 90, 10, "", "In battles, the opponent switches. In the wild, the Pokémon runs.", -1, 5 ],
  [ Moves.INCINERATE, "Incinerate", Type.FIRE, MOVE_CATEGORY.SPECIAL, 60, 100, 15, "", "Destroys the target's held berry.", -1, 5 ],
  [ Moves.QUASH, "Quash", Type.DARK, MOVE_CATEGORY.STATUS, -1, 100, 15, "", "Makes the target act last this turn.", -1, 5 ],
  [ Moves.ACROBATICS, "Acrobatics", Type.FLYING, MOVE_CATEGORY.PHYSICAL, 55, 100, 15, "TM14", "Stronger when the user does not have a held item.", -1, 5 ],
  [ Moves.REFLECT_TYPE, "Reflect Type", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "User becomes the target's type.", -1, 5 ],
  [ Moves.RETALIATE, "Retaliate", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 70, 100, 5, "", "Inflicts double damage if a teammate fainted on the last turn.", -1, 5 ],
  [ Moves.FINAL_GAMBIT, "Final Gambit", Type.FIGHTING, MOVE_CATEGORY.SPECIAL, -1, 100, 5, "", "Inflicts damage equal to the user's remaining HP. User faints.", -1, 5 ],
  [ Moves.BESTOW, "Bestow", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 15, "", "Gives the user's held item to the target.", -1, 5 ],
  [ Moves.INFERNO, "Inferno", Type.FIRE, MOVE_CATEGORY.SPECIAL, 100, 50, 5, "", "Burns opponent.", 100, 5 ],
  [ Moves.WATER_PLEDGE, "Water Pledge", Type.WATER, MOVE_CATEGORY.SPECIAL, 80, 100, 10, "TM145", "Added effects appear if preceded by Fire Pledge or succeeded by Grass Pledge.", -1, 5 ],
  [ Moves.FIRE_PLEDGE, "Fire Pledge", Type.FIRE, MOVE_CATEGORY.SPECIAL, 80, 100, 10, "TM144", "Added effects appear if combined with Grass Pledge or Water Pledge.", -1, 5 ],
  [ Moves.GRASS_PLEDGE, "Grass Pledge", Type.GRASS, MOVE_CATEGORY.SPECIAL, 80, 100, 10, "TM146", "Added effects appear if preceded by Water Pledge or succeeded by Fire Pledge.", -1, 5 ],
  [ Moves.VOLT_SWITCH, "Volt Switch", Type.ELECTRIC, MOVE_CATEGORY.SPECIAL, 70, 100, 20, "TM48", "User must switch out after attacking.", -1, 5 ],
  [ Moves.STRUGGLE_BUG, "Struggle Bug", Type.BUG, MOVE_CATEGORY.SPECIAL, 50, 100, 20, "TM15", "Lowers opponent's Special Attack.", 100, 5 ],
  [ Moves.BULLDOZE, "Bulldoze", Type.GROUND, MOVE_CATEGORY.PHYSICAL, 60, 100, 20, "TM28", "Lowers opponent's Speed.", 100, 5 ],
  [ Moves.FROST_BREATH, "Frost Breath", Type.ICE, MOVE_CATEGORY.SPECIAL, 60, 90, 10, "", "Always results in a critical hit.", 100, 5 ],
  [ Moves.DRAGON_TAIL, "Dragon Tail", Type.DRAGON, MOVE_CATEGORY.PHYSICAL, 60, 90, 10, "TM44", "In battles, the opponent switches. In the wild, the Pokémon runs.", -1, 5 ],
  [ Moves.WORK_UP, "Work Up", Type.NORMAL, MOVE_CATEGORY.STATUS, -1, -1, 30, "", "Raises user's Attack and Special Attack.", -1, 5 ],
  [ Moves.ELECTROWEB, "Electroweb", Type.ELECTRIC, MOVE_CATEGORY.SPECIAL, 55, 95, 15, "", "Lowers opponent's Speed.", 100, 5 ],
  [ Moves.WILD_CHARGE, "Wild Charge", Type.ELECTRIC, MOVE_CATEGORY.PHYSICAL, 90, 100, 15, "TM147", "User receives recoil damage.", -1, 5 ],
  [ Moves.DRILL_RUN, "Drill Run", Type.GROUND, MOVE_CATEGORY.PHYSICAL, 80, 95, 10, "TM106", "High critical hit ratio.", -1, 5 ],
  [ Moves.DUAL_CHOP, "Dual Chop", Type.DRAGON, MOVE_CATEGORY.PHYSICAL, 40, 90, 15, "", "Hits twice in one turn.", -1, 5 ],
  [ Moves.HEART_STAMP, "Heart Stamp", Type.PSYCHIC, MOVE_CATEGORY.PHYSICAL, 60, 100, 25, "", "May cause flinching.", 30, 5 ],
  [ Moves.HORN_LEECH, "Horn Leech", Type.GRASS, MOVE_CATEGORY.PHYSICAL, 75, 100, 10, "", "User recovers half the HP inflicted on opponent.", -1, 5 ],
  [ Moves.SACRED_SWORD, "Sacred Sword", Type.FIGHTING, MOVE_CATEGORY.PHYSICAL, 90, 100, 15, "", "Ignores opponent's stat changes.", -1, 5 ],
  [ Moves.RAZOR_SHELL, "Razor Shell", Type.WATER, MOVE_CATEGORY.PHYSICAL, 75, 95, 10, "", "May lower opponent's Defense.", 50, 5 ],
  [ Moves.HEAT_CRASH, "Heat Crash", Type.FIRE, MOVE_CATEGORY.PHYSICAL, -1, 100, 10, "", "The heavier the user, the stronger the attack.", -1, 5 ],
  [ Moves.LEAF_TORNADO, "Leaf Tornado", Type.GRASS, MOVE_CATEGORY.SPECIAL, 65, 90, 10, "", "May lower opponent's Accuracy.", 50, 5 ],
  [ Moves.STEAMROLLER, "Steamroller", Type.BUG, MOVE_CATEGORY.PHYSICAL, 65, 100, 20, "", "May cause flinching.", 30, 5 ],
  [ Moves.COTTON_GUARD, "Cotton Guard", Type.GRASS, MOVE_CATEGORY.STATUS, -1, -1, 10, "", "Drastically raises user's Defense.", -1, 5 ],
  [ Moves.NIGHT_DAZE, "Night Daze", Type.DARK, MOVE_CATEGORY.SPECIAL, 85, 95, 10, "", "May lower opponent's Accuracy.", 40, 5 ],
  [ Moves.PSYSTRIKE, "Psystrike", Type.PSYCHIC, MOVE_CATEGORY.SPECIAL, 100, 100, 10, "", "Inflicts damage based on the target's Defense, not Special Defense.", -1, 5 ],
  [ Moves.TAIL_SLAP, "Tail Slap", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 25, 85, 10, "", "Hits 2-5 times in one turn.", -1, 5 ],
  [ Moves.HURRICANE, "Hurricane", Type.FLYING, MOVE_CATEGORY.SPECIAL, 110, 70, 10, "TM160", "May confuse opponent.", 30, 5 ],
  [ Moves.HEAD_CHARGE, "Head Charge", Type.NORMAL, MOVE_CATEGORY.PHYSICAL, 120, 100, 15, "", "User receives recoil damage.", -1, 5 ],
  [ Moves.GEAR_GRIND, "Gear Grind", Type.STEEL, MOVE_CATEGORY.PHYSICAL, 50, 85, 15, "", "Hits twice in one turn.", -1, 5 ],
  [ Moves.SEARING_SHOT, "Searing Shot", Type.FIRE, MOVE_CATEGORY.SPECIAL, 100, 100, 5, "", "May burn opponent.", 30, 5 ],
  [ Moves.TECHNO_BLAST, "Techno Blast", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 120, 100, 5, "", "Type depends on the Drive being held.", -1, 5 ],
  [ Moves.RELIC_SONG, "Relic Song", Type.NORMAL, MOVE_CATEGORY.SPECIAL, 75, 100, 10, "", "May put the target to sleep.", 10, 5 ],
  [ Moves.SECRET_SWORD, "Secret Sword", Type.FIGHTING, MOVE_CATEGORY.SPECIAL, 85, 100, 10, "", "Inflicts damage based on the target's Defense, not Special Defense.", -1, 5 ],
  [ Moves.GLACIATE, "Glaciate", Type.ICE, MOVE_CATEGORY.SPECIAL, 65, 95, 10, "", "Lowers opponent's Speed.", 100, 5 ],
  [ Moves.BOLT_STRIKE, "Bolt Strike", Type.ELECTRIC, MOVE_CATEGORY.PHYSICAL, 130, 85, 5, "", "May paralyze opponent.", 20, 5 ],
  [ Moves.BLUE_FLARE, "Blue Flare", Type.FIRE, MOVE_CATEGORY.SPECIAL, 130, 85, 5, "", "May burn opponent.", 20, 5 ],
  [ Moves.FIERY_DANCE, "Fiery Dance", Type.FIRE, MOVE_CATEGORY.SPECIAL, 80, 100, 10, "", "May raise user's Special Attack.", 50, 5 ],
  [ Moves.FREEZE_SHOCK, "Freeze Shock", Type.ICE, MOVE_CATEGORY.PHYSICAL, 140, 90, 5, "", "Charges on first turn, attacks on second. May paralyze opponent.", 30, 5 ],
  [ Moves.ICE_BURN, "Ice Burn", Type.ICE, MOVE_CATEGORY.SPECIAL, 140, 90, 5, "", "Charges on first turn, attacks on second. May burn opponent.", 30, 5 ],
  [ Moves.SNARL, "Snarl", Type.DARK, MOVE_CATEGORY.SPECIAL, 55, 95, 15, "TM30", "Lowers opponent's Special Attack.", 100, 5 ],
  [ Moves.ICICLE_CRASH, "Icicle Crash", Type.ICE, MOVE_CATEGORY.PHYSICAL, 85, 90, 10, "", "May cause flinching.", 30, 5 ],
  [ Moves.V_CREATE, "V-create", Type.FIRE, MOVE_CATEGORY.PHYSICAL, 180, 95, 5, "", "Lowers user's Defense, Special Defense and Speed.", 100, 5 ],
  [ Moves.FUSION_FLARE, "Fusion Flare", Type.FIRE, MOVE_CATEGORY.SPECIAL, 100, 100, 5, "", "Power increases if Fusion Bolt is used in the same turn.", -1, 5 ],
  [ Moves.FUSION_BOLT, "Fusion Bolt", Type.ELECTRIC, MOVE_CATEGORY.PHYSICAL, 100, 100, 5, "", "Power increases if Fusion Flare is used in the same turn.", -1, 5 ]
].map(m => {
  let i = 0;
  return new Move(m[i++], m[i++], m[i++], m[i++], m[i++], m[i++], m[i++], m[i++], m[i++], m[i++], m[i++]);
});